-- generateMissingDataSQL.ts による自動生成
-- 対象: 908 件

UPDATE characters SET favourites = 19 WHERE character_id = 'CH013699';
UPDATE characters SET favourites = 385 WHERE character_id = 'CH013733';
UPDATE characters SET favourites = 4774 WHERE character_id = 'CH013722';
UPDATE characters SET favourites = 4 WHERE character_id = 'CH013734';
UPDATE characters SET favourites = 59 WHERE character_id = 'CH013732';
UPDATE characters SET favourites = 3 WHERE character_id = 'CH013726';
UPDATE characters SET favourites = 475 WHERE character_id = 'CH013701';
UPDATE characters SET favourites = 5 WHERE character_id = 'CH013704';
UPDATE characters SET favourites = 5 WHERE character_id = 'CH013718';
UPDATE characters SET favourites = 83 WHERE character_id = 'CH013696';
UPDATE characters SET favourites = 73 WHERE character_id = 'CH013725';
UPDATE characters SET favourites = 17 WHERE character_id = 'CH013727';
UPDATE characters SET favourites = 1825 WHERE character_id = 'CH013721';
UPDATE characters SET favourites = 468 WHERE character_id = 'CH013728';
UPDATE characters SET favourites = 176 WHERE character_id = 'CH013724';
UPDATE characters SET favourites = 190 WHERE character_id = 'CH013717';
UPDATE characters SET favourites = 177 WHERE character_id = 'CH013706';
UPDATE characters SET favourites = 488 WHERE character_id = 'CH013705';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005453';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005454';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005455';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005470';
UPDATE characters SET role = 'SUPPORTING', favourites = 32 WHERE character_id = 'CH005465';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005464';
UPDATE characters SET role = 'MAIN', favourites = 62 WHERE character_id = 'CH005446';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005459';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005467';
UPDATE characters SET role = 'SUPPORTING', favourites = 14 WHERE character_id = 'CH005463';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005460';
UPDATE characters SET favourites = 31 WHERE character_id = 'CH003729';
UPDATE characters SET favourites = 15 WHERE character_id = 'CH003710';
UPDATE characters SET favourites = 32 WHERE character_id = 'CH003714';
UPDATE characters SET favourites = 67 WHERE character_id = 'CH003741';
UPDATE characters SET favourites = 116 WHERE character_id = 'CH003727';
UPDATE characters SET favourites = 677 WHERE character_id = 'CH003738';
UPDATE characters SET favourites = 16 WHERE character_id = 'CH003720';
UPDATE characters SET favourites = 7 WHERE character_id = 'CH003709';
UPDATE characters SET favourites = 12 WHERE character_id = 'CH003719';
UPDATE characters SET favourites = 1055 WHERE character_id = 'CH003707';
UPDATE characters SET favourites = 9 WHERE character_id = 'CH003737';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH013775';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH013773';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH013776';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013774';
UPDATE characters SET role = 'SUPPORTING', favourites = 53 WHERE character_id = 'CH013778';
UPDATE characters SET role = 'SUPPORTING', favourites = 34 WHERE character_id = 'CH013780';
UPDATE characters SET role = 'SUPPORTING', favourites = 64 WHERE character_id = 'CH013777';
UPDATE characters SET role = 'MAIN', favourites = 335 WHERE character_id = 'CH013771';
UPDATE characters SET role = 'MAIN', favourites = 101 WHERE character_id = 'CH013770';
UPDATE characters SET role = 'SUPPORTING', favourites = 114 WHERE character_id = 'CH013779';
UPDATE characters SET role = 'MAIN', favourites = 275 WHERE character_id = 'CH013772';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005484';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005491';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005479';
UPDATE characters SET role = 'SUPPORTING', favourites = 86 WHERE character_id = 'CH005475';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005481';
UPDATE characters SET role = 'SUPPORTING', favourites = 31 WHERE character_id = 'CH005480';
UPDATE characters SET role = 'SUPPORTING', favourites = 251 WHERE character_id = 'CH005477';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005478';
UPDATE characters SET role = 'SUPPORTING', favourites = 38 WHERE character_id = 'CH005483';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005490';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005493';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005476';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005485';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005486';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005487';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH005488';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005489';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005482';
UPDATE characters SET role = 'MAIN', favourites = 782 WHERE character_id = 'CH005474';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005497';
UPDATE characters SET role = 'SUPPORTING', favourites = 29 WHERE character_id = 'CH005498';
UPDATE characters SET role = 'SUPPORTING', favourites = 36 WHERE character_id = 'CH005496';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005495';
UPDATE characters SET role = 'SUPPORTING', favourites = 22 WHERE character_id = 'CH005500';
UPDATE characters SET role = 'SUPPORTING', favourites = 12 WHERE character_id = 'CH005502';
UPDATE characters SET role = 'SUPPORTING', favourites = 29 WHERE character_id = 'CH005499';
UPDATE characters SET role = 'SUPPORTING', favourites = 22 WHERE character_id = 'CH005501';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005503';
UPDATE characters SET role = 'SUPPORTING', favourites = 142 WHERE character_id = 'CH005513';
UPDATE characters SET role = 'MAIN', favourites = 5106 WHERE character_id = 'CH005505';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005515';
UPDATE characters SET role = 'SUPPORTING', favourites = 50 WHERE character_id = 'CH005512';
UPDATE characters SET role = 'SUPPORTING', favourites = 95 WHERE character_id = 'CH005514';
UPDATE characters SET role = 'MAIN', favourites = 913 WHERE character_id = 'CH005509';
UPDATE characters SET role = 'MAIN', favourites = 536 WHERE character_id = 'CH005508';
UPDATE characters SET role = 'SUPPORTING', favourites = 62 WHERE character_id = 'CH005511';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005510';
UPDATE characters SET role = 'MAIN', favourites = 174 WHERE character_id = 'CH005506';
UPDATE characters SET role = 'MAIN', favourites = 450 WHERE character_id = 'CH005507';
UPDATE characters SET role = 'MAIN', favourites = 3157 WHERE character_id = 'CH005504';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005540';
UPDATE characters SET role = 'SUPPORTING', favourites = 256 WHERE character_id = 'CH005531';
UPDATE characters SET role = 'SUPPORTING', favourites = 26 WHERE character_id = 'CH005537';
UPDATE characters SET role = 'SUPPORTING', favourites = 12 WHERE character_id = 'CH005539';
UPDATE characters SET role = 'SUPPORTING', favourites = 567 WHERE character_id = 'CH005542';
UPDATE characters SET role = 'MAIN', favourites = 144 WHERE character_id = 'CH005524';
UPDATE characters SET role = 'SUPPORTING', favourites = 2344 WHERE character_id = 'CH005546';
UPDATE characters SET role = 'SUPPORTING', favourites = 127 WHERE character_id = 'CH005529';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH005525';
UPDATE characters SET role = 'SUPPORTING', favourites = 15 WHERE character_id = 'CH005530';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005541';
UPDATE characters SET role = 'SUPPORTING', favourites = 15 WHERE character_id = 'CH005532';
UPDATE characters SET role = 'SUPPORTING', favourites = 13 WHERE character_id = 'CH005534';
UPDATE characters SET role = 'MAIN', favourites = 2602 WHERE character_id = 'CH005522';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005535';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005544';
UPDATE characters SET role = 'SUPPORTING', favourites = 382 WHERE character_id = 'CH005528';
UPDATE characters SET role = 'SUPPORTING', favourites = 107 WHERE character_id = 'CH005533';
UPDATE characters SET role = 'SUPPORTING', favourites = 848 WHERE character_id = 'CH005527';
UPDATE characters SET role = 'SUPPORTING', favourites = 217 WHERE character_id = 'CH005526';
UPDATE characters SET role = 'MAIN', favourites = 222 WHERE character_id = 'CH005523';
UPDATE characters SET role = 'SUPPORTING', favourites = 49 WHERE character_id = 'CH005545';
UPDATE characters SET role = 'SUPPORTING', favourites = 92 WHERE character_id = 'CH005543';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005538';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH005536';
UPDATE characters SET role = 'MAIN', favourites = 249 WHERE character_id = 'CH005521';
UPDATE characters SET role = 'SUPPORTING', favourites = 1406 WHERE character_id = 'CH005547';
UPDATE characters SET role = 'MAIN', favourites = 5197 WHERE character_id = 'CH005520';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005557';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005561';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005563';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005556';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005562';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005558';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005559';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005560';
UPDATE characters SET role = 'MAIN', favourites = 34 WHERE character_id = 'CH005548';
UPDATE characters SET role = 'MAIN', favourites = 234 WHERE character_id = 'CH005549';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005552';
UPDATE characters SET role = 'SUPPORTING', favourites = 47 WHERE character_id = 'CH005553';
UPDATE characters SET role = 'SUPPORTING', favourites = 124 WHERE character_id = 'CH005554';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005551';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005550';
UPDATE characters SET role = 'SUPPORTING', favourites = 87 WHERE character_id = 'CH005555';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005565';
UPDATE characters SET role = 'SUPPORTING', favourites = 21 WHERE character_id = 'CH005574';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005573';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005595';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005594';
UPDATE characters SET role = 'SUPPORTING', favourites = 2557 WHERE character_id = 'CH005593';
UPDATE characters SET role = 'SUPPORTING', favourites = 214 WHERE character_id = 'CH005577';
UPDATE characters SET role = 'SUPPORTING', favourites = 291 WHERE character_id = 'CH005575';
UPDATE characters SET role = 'SUPPORTING', favourites = 24 WHERE character_id = 'CH005582';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005570';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005586';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH005571';
UPDATE characters SET role = 'SUPPORTING', favourites = 935 WHERE character_id = 'CH005585';
UPDATE characters SET role = 'SUPPORTING', favourites = 94 WHERE character_id = 'CH005584';
UPDATE characters SET role = 'SUPPORTING', favourites = 22 WHERE character_id = 'CH005583';
UPDATE characters SET role = 'SUPPORTING', favourites = 312 WHERE character_id = 'CH005576';
UPDATE characters SET role = 'SUPPORTING', favourites = 14 WHERE character_id = 'CH005587';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005569';
UPDATE characters SET role = 'MAIN', favourites = 3993 WHERE character_id = 'CH005564';
UPDATE characters SET role = 'SUPPORTING', favourites = 17 WHERE character_id = 'CH005566';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005596';
UPDATE characters SET role = 'SUPPORTING', favourites = 489 WHERE character_id = 'CH005597';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005598';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005578';
UPDATE characters SET role = 'SUPPORTING', favourites = 125 WHERE character_id = 'CH005579';
UPDATE characters SET role = 'SUPPORTING', favourites = 34 WHERE character_id = 'CH005580';
UPDATE characters SET role = 'SUPPORTING', favourites = 607 WHERE character_id = 'CH005581';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005592';
UPDATE characters SET role = 'SUPPORTING', favourites = 57 WHERE character_id = 'CH005568';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005590';
UPDATE characters SET role = 'SUPPORTING', favourites = 396 WHERE character_id = 'CH005567';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005591';
UPDATE characters SET role = 'SUPPORTING', favourites = 2466 WHERE character_id = 'CH005589';
UPDATE characters SET role = 'SUPPORTING', favourites = 454 WHERE character_id = 'CH005588';
UPDATE characters SET role = 'SUPPORTING', favourites = 244 WHERE character_id = 'CH005606';
UPDATE characters SET role = 'SUPPORTING', favourites = 125 WHERE character_id = 'CH005605';
UPDATE characters SET role = 'SUPPORTING', favourites = 38 WHERE character_id = 'CH005616';
UPDATE characters SET role = 'MAIN', favourites = 85 WHERE character_id = 'CH005602';
UPDATE characters SET role = 'SUPPORTING', favourites = 361 WHERE character_id = 'CH005610';
UPDATE characters SET role = 'SUPPORTING', favourites = 64 WHERE character_id = 'CH005615';
UPDATE characters SET role = 'SUPPORTING', favourites = 19 WHERE character_id = 'CH005618';
UPDATE characters SET role = 'SUPPORTING', favourites = 181 WHERE character_id = 'CH005614';
UPDATE characters SET role = 'SUPPORTING', favourites = 61 WHERE character_id = 'CH005612';
UPDATE characters SET role = 'SUPPORTING', favourites = 95 WHERE character_id = 'CH005611';
UPDATE characters SET role = 'SUPPORTING', favourites = 60 WHERE character_id = 'CH005609';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH005607';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005608';
UPDATE characters SET role = 'MAIN', favourites = 356 WHERE character_id = 'CH005599';
UPDATE characters SET role = 'MAIN', favourites = 144 WHERE character_id = 'CH005601';
UPDATE characters SET role = 'SUPPORTING', favourites = 177 WHERE character_id = 'CH005617';
UPDATE characters SET role = 'MAIN', favourites = 384 WHERE character_id = 'CH005603';
UPDATE characters SET role = 'SUPPORTING', favourites = 125 WHERE character_id = 'CH005613';
UPDATE characters SET role = 'SUPPORTING', favourites = 149 WHERE character_id = 'CH005619';
UPDATE characters SET role = 'MAIN', favourites = 42 WHERE character_id = 'CH005600';
UPDATE characters SET role = 'MAIN', favourites = 71 WHERE character_id = 'CH005604';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005634';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005624';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005626';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005637';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005633';
UPDATE characters SET role = 'SUPPORTING', favourites = 29 WHERE character_id = 'CH005627';
UPDATE characters SET role = 'MAIN', favourites = 155 WHERE character_id = 'CH005621';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005631';
UPDATE characters SET role = 'MAIN', favourites = 24 WHERE character_id = 'CH005620';
UPDATE characters SET role = 'SUPPORTING', favourites = 31 WHERE character_id = 'CH005630';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH005623';
UPDATE characters SET role = 'SUPPORTING', favourites = 29 WHERE character_id = 'CH005628';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005629';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005635';
UPDATE characters SET role = 'SUPPORTING', favourites = 19 WHERE character_id = 'CH005632';
UPDATE characters SET role = 'MAIN', favourites = 98 WHERE character_id = 'CH005622';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005625';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005636';
UPDATE characters SET role = 'SUPPORTING', favourites = 22 WHERE character_id = 'CH005642';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005649';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005645';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005652';
UPDATE characters SET role = 'MAIN', favourites = 1235 WHERE character_id = 'CH005639';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005643';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005646';
UPDATE characters SET role = 'SUPPORTING', favourites = 14 WHERE character_id = 'CH005647';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005641';
UPDATE characters SET role = 'MAIN', favourites = 1211 WHERE character_id = 'CH005638';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005651';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005640';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005650';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005648';
UPDATE characters SET favourites = 1 WHERE character_id = 'CH003794';
UPDATE characters SET favourites = 670 WHERE character_id = 'CH003781';
UPDATE characters SET favourites = 3 WHERE character_id = 'CH003770';
UPDATE characters SET favourites = 7 WHERE character_id = 'CH003763';
UPDATE characters SET favourites = 19 WHERE character_id = 'CH003796';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005687';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005686';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005684';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005683';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005691';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005682';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005681';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005701';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005680';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005702';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005699';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005700';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005677';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005692';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005678';
UPDATE characters SET role = 'SUPPORTING', favourites = 108 WHERE character_id = 'CH005676';
UPDATE characters SET role = 'MAIN', favourites = 128 WHERE character_id = 'CH005675';
UPDATE characters SET role = 'MAIN', favourites = 147 WHERE character_id = 'CH005674';
UPDATE characters SET role = 'SUPPORTING', favourites = 18 WHERE character_id = 'CH005696';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005693';
UPDATE characters SET role = 'SUPPORTING', favourites = 117 WHERE character_id = 'CH005685';
UPDATE characters SET role = 'SUPPORTING', favourites = 118 WHERE character_id = 'CH005698';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005695';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005679';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005689';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005688';
UPDATE characters SET role = 'SUPPORTING', favourites = 134 WHERE character_id = 'CH005690';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005712';
UPDATE characters SET role = 'MAIN', favourites = 53 WHERE character_id = 'CH005703';
UPDATE characters SET role = 'MAIN', favourites = 76 WHERE character_id = 'CH005704';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH005710';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005711';
UPDATE characters SET role = 'SUPPORTING', favourites = 34 WHERE character_id = 'CH005709';
UPDATE characters SET role = 'MAIN', favourites = 57 WHERE character_id = 'CH005705';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005706';
UPDATE characters SET role = 'SUPPORTING', favourites = 13 WHERE character_id = 'CH005708';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005707';
UPDATE characters SET role = 'MAIN', favourites = 9 WHERE character_id = 'CH005717';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005727';
UPDATE characters SET role = 'MAIN', favourites = 65 WHERE character_id = 'CH005714';
UPDATE characters SET role = 'MAIN', favourites = 44 WHERE character_id = 'CH005715';
UPDATE characters SET role = 'MAIN', favourites = 28 WHERE character_id = 'CH005716';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005728';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005721';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005729';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005730';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005725';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005718';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005720';
UPDATE characters SET role = 'MAIN', favourites = 32 WHERE character_id = 'CH005713';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005726';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005724';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005723';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005722';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005719';
UPDATE characters SET role = 'SUPPORTING', favourites = 62 WHERE character_id = 'CH005737';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005739';
UPDATE characters SET role = 'MAIN', favourites = 48 WHERE character_id = 'CH005733';
UPDATE characters SET role = 'MAIN', favourites = 48 WHERE character_id = 'CH005731';
UPDATE characters SET role = 'MAIN', favourites = 39 WHERE character_id = 'CH005732';
UPDATE characters SET role = 'SUPPORTING', favourites = 17 WHERE character_id = 'CH005734';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005740';
UPDATE characters SET role = 'SUPPORTING', favourites = 18 WHERE character_id = 'CH005736';
UPDATE characters SET role = 'SUPPORTING', favourites = 21 WHERE character_id = 'CH005738';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005744';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005749';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH005751';
UPDATE characters SET role = 'MAIN', favourites = 18 WHERE character_id = 'CH005741';
UPDATE characters SET role = 'MAIN', favourites = 8 WHERE character_id = 'CH005742';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005743';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005748';
UPDATE characters SET role = 'SUPPORTING', favourites = 81 WHERE character_id = 'CH005752';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005745';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005747';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005746';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH005750';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005771';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005764';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005756';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005766';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005767';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005769';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005758';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005768';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005772';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005757';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005760';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005761';
UPDATE characters SET role = 'MAIN', favourites = 26 WHERE character_id = 'CH005755';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005770';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005762';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH005765';
UPDATE characters SET role = 'MAIN', favourites = 8 WHERE character_id = 'CH005753';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005763';
UPDATE characters SET role = 'MAIN', favourites = 16 WHERE character_id = 'CH005754';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH005775';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005782';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005781';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005778';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005783';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH005777';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005774';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005780';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005784';
UPDATE characters SET role = 'MAIN', favourites = 40 WHERE character_id = 'CH005785';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005801';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005800';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005799';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005802';
UPDATE characters SET role = 'MAIN', favourites = 8 WHERE character_id = 'CH005786';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005791';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005794';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005788';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005793';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005789';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005795';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005803';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005805';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005806';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005804';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005796';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005792';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005787';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005790';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005797';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005798';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005851';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005857';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005858';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005860';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005859';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005862';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005856';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH005822';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH005839';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005834';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005853';
UPDATE characters SET role = 'SUPPORTING', favourites = 28 WHERE character_id = 'CH005833';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH005832';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005831';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH005830';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005829';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH005827';
UPDATE characters SET role = 'SUPPORTING', favourites = 31 WHERE character_id = 'CH005826';
UPDATE characters SET role = 'SUPPORTING', favourites = 67 WHERE character_id = 'CH005825';
UPDATE characters SET role = 'SUPPORTING', favourites = 76 WHERE character_id = 'CH005824';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005823';
UPDATE characters SET role = 'MAIN', favourites = 16 WHERE character_id = 'CH005813';
UPDATE characters SET role = 'MAIN', favourites = 150 WHERE character_id = 'CH005809';
UPDATE characters SET role = 'SUPPORTING', favourites = 32 WHERE character_id = 'CH005837';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005855';
UPDATE characters SET role = 'SUPPORTING', favourites = 77 WHERE character_id = 'CH005854';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005850';
UPDATE characters SET role = 'SUPPORTING', favourites = 28 WHERE character_id = 'CH005849';
UPDATE characters SET role = 'SUPPORTING', favourites = 20 WHERE character_id = 'CH005848';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005847';
UPDATE characters SET role = 'MAIN', favourites = 84 WHERE character_id = 'CH005807';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005840';
UPDATE characters SET role = 'SUPPORTING', favourites = 24 WHERE character_id = 'CH005838';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005836';
UPDATE characters SET role = 'SUPPORTING', favourites = 52 WHERE character_id = 'CH005835';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005821';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH005820';
UPDATE characters SET role = 'SUPPORTING', favourites = 24 WHERE character_id = 'CH005819';
UPDATE characters SET role = 'MAIN', favourites = 96 WHERE character_id = 'CH005818';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005828';
UPDATE characters SET role = 'SUPPORTING', favourites = 142 WHERE character_id = 'CH005845';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH005843';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH005842';
UPDATE characters SET role = 'SUPPORTING', favourites = 138 WHERE character_id = 'CH005841';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005844';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH005816';
UPDATE characters SET role = 'MAIN', favourites = 32 WHERE character_id = 'CH005810';
UPDATE characters SET role = 'MAIN', favourites = 31 WHERE character_id = 'CH005811';
UPDATE characters SET role = 'MAIN', favourites = 18 WHERE character_id = 'CH005812';
UPDATE characters SET role = 'MAIN', favourites = 55 WHERE character_id = 'CH005815';
UPDATE characters SET role = 'MAIN', favourites = 5 WHERE character_id = 'CH005814';
UPDATE characters SET role = 'MAIN', favourites = 71 WHERE character_id = 'CH005808';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH005846';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH003817';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH003903';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH003889';
UPDATE characters SET role = 'SUPPORTING', favourites = 19 WHERE character_id = 'CH013910';
UPDATE characters SET role = 'SUPPORTING', favourites = 88 WHERE character_id = 'CH013906';
UPDATE characters SET role = 'MAIN', favourites = 33 WHERE character_id = 'CH013081';
UPDATE characters SET role = 'MAIN', favourites = 10 WHERE character_id = 'CH013080';
UPDATE characters SET role = 'MAIN', favourites = 8 WHERE character_id = 'CH013082';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013106';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013105';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013104';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013102';
UPDATE characters SET role = 'MAIN', favourites = 28 WHERE character_id = 'CH013101';
UPDATE characters SET role = 'MAIN', favourites = 18 WHERE character_id = 'CH013100';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013108';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013103';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013107';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013111';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013114';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013116';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013112';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013115';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013113';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013110';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013109';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013119';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013125';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013124';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013127';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013123';
UPDATE characters SET role = 'MAIN', favourites = 36 WHERE character_id = 'CH013117';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013126';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013122';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013121';
UPDATE characters SET role = 'MAIN', favourites = 23 WHERE character_id = 'CH013118';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013120';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013135';
UPDATE characters SET role = 'MAIN', favourites = 81 WHERE character_id = 'CH013128';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013132';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013131';
UPDATE characters SET role = 'SUPPORTING', favourites = 20 WHERE character_id = 'CH013130';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013133';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013134';
UPDATE characters SET role = 'MAIN', favourites = 9 WHERE character_id = 'CH013129';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013140';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013138';
UPDATE characters SET role = 'MAIN', favourites = 41 WHERE character_id = 'CH013137';
UPDATE characters SET role = 'MAIN', favourites = 3 WHERE character_id = 'CH013136';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH013139';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013148';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013144';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013143';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013149';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013150';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013145';
UPDATE characters SET role = 'MAIN', favourites = 25 WHERE character_id = 'CH013141';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013147';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013146';
UPDATE characters SET role = 'MAIN', favourites = 6 WHERE character_id = 'CH013142';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013157';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013153';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013154';
UPDATE characters SET role = 'MAIN', favourites = 12 WHERE character_id = 'CH013151';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013155';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH013152';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH013156';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013158';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH003954';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005870';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005874';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005877';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005865';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005866';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005864';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005868';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005876';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005871';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005875';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005867';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005869';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005879';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005878';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005873';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005872';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005863';
UPDATE characters SET favourites = 567 WHERE character_id = 'CH003970';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005880';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005885';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005884';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005882';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH005883';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005881';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005887';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005888';
UPDATE characters SET role = 'MAIN' WHERE character_id = 'CH005890';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005930';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005904';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005903';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005902';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005901';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH005891';
UPDATE characters SET role = 'MAIN', favourites = 5 WHERE character_id = 'CH005889';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005900';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005917';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH005897';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005898';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005936';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005907';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH005892';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005916';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005935';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005941';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005914';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005915';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005938';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005899';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005925';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005909';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005927';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005926';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005924';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005933';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005934';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005940';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005942';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005931';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005928';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005929';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005923';
UPDATE characters SET role = 'MAIN', favourites = 0 WHERE character_id = 'CH005895';
UPDATE characters SET role = 'MAIN', favourites = 0 WHERE character_id = 'CH005894';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005910';
UPDATE characters SET role = 'MAIN', favourites = 0 WHERE character_id = 'CH005896';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005912';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005937';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005913';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005920';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005921';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005922';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005908';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005911';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005939';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005906';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005905';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005964';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005993';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005967';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006001';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006002';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005984';
UPDATE characters SET role = 'MAIN', favourites = 22 WHERE character_id = 'CH005944';
UPDATE characters SET role = 'MAIN', favourites = 18 WHERE character_id = 'CH005945';
UPDATE characters SET role = 'MAIN', favourites = 10 WHERE character_id = 'CH005946';
UPDATE characters SET role = 'MAIN', favourites = 11 WHERE character_id = 'CH005947';
UPDATE characters SET role = 'MAIN', favourites = 10 WHERE character_id = 'CH005948';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005990';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005992';
UPDATE characters SET role = 'MAIN', favourites = 6 WHERE character_id = 'CH005949';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH005951';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005953';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005954';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH005955';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH005957';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005958';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005959';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005960';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005961';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005963';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005965';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005966';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005968';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005969';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005970';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005971';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005972';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005973';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005974';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005975';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005976';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005977';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005978';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH005979';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005980';
UPDATE characters SET role = 'MAIN', favourites = 27 WHERE character_id = 'CH005943';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005981';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005999';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005982';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005983';
UPDATE characters SET role = 'MAIN', favourites = 21 WHERE character_id = 'CH005950';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006003';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH005962';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005952';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005956';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005995';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005991';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005985';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005986';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005987';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005988';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005989';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005994';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005996';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005997';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH005998';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006000';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006043';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006037';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH006055';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006064';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006038';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006060';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006030';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006050';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006052';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006053';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH006013';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH006031';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH006014';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH006057';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006026';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH006017';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH006018';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH006021';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006032';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006063';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006062';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006045';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006056';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006042';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006039';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006040';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006029';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006036';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006054';
UPDATE characters SET role = 'MAIN', favourites = 9 WHERE character_id = 'CH006004';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH006027';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006065';
UPDATE characters SET role = 'MAIN', favourites = 9 WHERE character_id = 'CH006005';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH006006';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006067';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006059';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH006012';
UPDATE characters SET role = 'MAIN', favourites = 3 WHERE character_id = 'CH006011';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH006010';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH006061';
UPDATE characters SET role = 'MAIN', favourites = 16 WHERE character_id = 'CH006009';
UPDATE characters SET role = 'MAIN', favourites = 20 WHERE character_id = 'CH006007';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH006016';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006020';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006051';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH006035';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH006034';
UPDATE characters SET role = 'SUPPORTING', favourites = 67 WHERE character_id = 'CH006033';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH006049';
UPDATE characters SET role = 'SUPPORTING', favourites = 12 WHERE character_id = 'CH006048';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006047';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006046';
UPDATE characters SET role = 'MAIN', favourites = 16 WHERE character_id = 'CH006008';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006028';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006025';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006024';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006023';
UPDATE characters SET role = 'SUPPORTING', favourites = 12 WHERE character_id = 'CH006022';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH006019';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006066';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006058';
UPDATE characters SET favourites = 4 WHERE character_id = 'CH004002';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006072';
UPDATE characters SET role = 'SUPPORTING', favourites = 1055 WHERE character_id = 'CH006070';
UPDATE characters SET role = 'MAIN', favourites = 944 WHERE character_id = 'CH006069';
UPDATE characters SET role = 'MAIN', favourites = 3526 WHERE character_id = 'CH006068';
UPDATE characters SET role = 'SUPPORTING', favourites = 2387 WHERE character_id = 'CH006076';
UPDATE characters SET role = 'SUPPORTING', favourites = 80 WHERE character_id = 'CH006079';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH006074';
UPDATE characters SET role = 'SUPPORTING', favourites = 25 WHERE character_id = 'CH006080';
UPDATE characters SET role = 'SUPPORTING', favourites = 70 WHERE character_id = 'CH006078';
UPDATE characters SET role = 'SUPPORTING', favourites = 335 WHERE character_id = 'CH006073';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH006075';
UPDATE characters SET role = 'SUPPORTING', favourites = 171 WHERE character_id = 'CH006111';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH006108';
UPDATE characters SET role = 'SUPPORTING', favourites = 646 WHERE character_id = 'CH006091';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH006114';
UPDATE characters SET role = 'SUPPORTING', favourites = 6356 WHERE character_id = 'CH006103';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH006104';
UPDATE characters SET role = 'SUPPORTING', favourites = 67 WHERE character_id = 'CH006105';
UPDATE characters SET role = 'SUPPORTING', favourites = 59 WHERE character_id = 'CH006089';
UPDATE characters SET role = 'SUPPORTING', favourites = 59 WHERE character_id = 'CH006106';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH006086';
UPDATE characters SET role = 'SUPPORTING', favourites = 15 WHERE character_id = 'CH006088';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH006085';
UPDATE characters SET role = 'MAIN', favourites = 11671 WHERE character_id = 'CH006084';
UPDATE characters SET role = 'MAIN', favourites = 5733 WHERE character_id = 'CH006081';
UPDATE characters SET role = 'SUPPORTING', favourites = 24 WHERE character_id = 'CH006112';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006090';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH006097';
UPDATE characters SET role = 'SUPPORTING', favourites = 100 WHERE character_id = 'CH006110';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH006109';
UPDATE characters SET role = 'SUPPORTING', favourites = 182 WHERE character_id = 'CH006113';
UPDATE characters SET role = 'SUPPORTING', favourites = 43 WHERE character_id = 'CH006096';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH006107';
UPDATE characters SET role = 'SUPPORTING', favourites = 231 WHERE character_id = 'CH006095';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH006094';
UPDATE characters SET role = 'SUPPORTING', favourites = 1783 WHERE character_id = 'CH006092';
UPDATE characters SET favourites = 15 WHERE character_id = 'CH004017';
UPDATE characters SET role = 'SUPPORTING', favourites = 207 WHERE character_id = 'CH006170';
UPDATE characters SET role = 'SUPPORTING', favourites = 7 WHERE character_id = 'CH006164';
UPDATE characters SET role = 'MAIN', favourites = 856 WHERE character_id = 'CH006157';
UPDATE characters SET role = 'MAIN', favourites = 891 WHERE character_id = 'CH006156';
UPDATE characters SET role = 'MAIN', favourites = 2305 WHERE character_id = 'CH006154';
UPDATE characters SET role = 'SUPPORTING', favourites = 10 WHERE character_id = 'CH006168';
UPDATE characters SET role = 'SUPPORTING', favourites = 263 WHERE character_id = 'CH006166';
UPDATE characters SET role = 'SUPPORTING', favourites = 115 WHERE character_id = 'CH006165';
UPDATE characters SET role = 'SUPPORTING', favourites = 47 WHERE character_id = 'CH006159';
UPDATE characters SET role = 'SUPPORTING', favourites = 89 WHERE character_id = 'CH006169';
UPDATE characters SET role = 'SUPPORTING', favourites = 338 WHERE character_id = 'CH006163';
UPDATE characters SET role = 'SUPPORTING', favourites = 41 WHERE character_id = 'CH006158';
UPDATE characters SET role = 'SUPPORTING', favourites = 48 WHERE character_id = 'CH006162';
UPDATE characters SET role = 'SUPPORTING', favourites = 51 WHERE character_id = 'CH006160';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH006167';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH013807';
UPDATE characters SET role = 'SUPPORTING' WHERE character_id = 'CH013814';
UPDATE characters SET role = 'SUPPORTING', favourites = 724 WHERE character_id = 'CH013786';
UPDATE characters SET role = 'SUPPORTING', favourites = 39 WHERE character_id = 'CH013787';
UPDATE characters SET role = 'SUPPORTING', favourites = 241 WHERE character_id = 'CH013836';
UPDATE characters SET role = 'SUPPORTING', favourites = 520 WHERE character_id = 'CH013788';
UPDATE characters SET role = 'SUPPORTING', favourites = 474 WHERE character_id = 'CH013789';
UPDATE characters SET role = 'SUPPORTING', favourites = 697 WHERE character_id = 'CH013817';
UPDATE characters SET role = 'SUPPORTING', favourites = 203 WHERE character_id = 'CH013818';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013819';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013838';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013833';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013791';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013803';
UPDATE characters SET role = 'SUPPORTING', favourites = 136 WHERE character_id = 'CH013834';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013813';
UPDATE characters SET role = 'SUPPORTING', favourites = 43 WHERE character_id = 'CH013812';
UPDATE characters SET role = 'SUPPORTING', favourites = 133 WHERE character_id = 'CH013811';
UPDATE characters SET role = 'SUPPORTING', favourites = 17 WHERE character_id = 'CH013809';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013808';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013806';
UPDATE characters SET role = 'SUPPORTING', favourites = 29 WHERE character_id = 'CH013831';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013830';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013828';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013821';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013794';
UPDATE characters SET role = 'SUPPORTING', favourites = 11 WHERE character_id = 'CH013795';
UPDATE characters SET role = 'SUPPORTING', favourites = 45 WHERE character_id = 'CH013796';
UPDATE characters SET role = 'SUPPORTING', favourites = 8 WHERE character_id = 'CH013797';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013798';
UPDATE characters SET role = 'SUPPORTING', favourites = 1740 WHERE character_id = 'CH013827';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013793';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013832';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013792';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013790';
UPDATE characters SET role = 'SUPPORTING', favourites = 14 WHERE character_id = 'CH013837';
UPDATE characters SET role = 'SUPPORTING', favourites = 434 WHERE character_id = 'CH013804';
UPDATE characters SET role = 'SUPPORTING', favourites = 1870 WHERE character_id = 'CH013801';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013800';
UPDATE characters SET role = 'SUPPORTING', favourites = 246 WHERE character_id = 'CH013823';
UPDATE characters SET role = 'SUPPORTING', favourites = 142 WHERE character_id = 'CH013822';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013805';
UPDATE characters SET role = 'MAIN', favourites = 3328 WHERE character_id = 'CH013781';
UPDATE characters SET role = 'MAIN', favourites = 23 WHERE character_id = 'CH013161';
UPDATE characters SET role = 'SUPPORTING', favourites = 9 WHERE character_id = 'CH013162';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013164';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013163';
UPDATE characters SET role = 'MAIN', favourites = 17 WHERE character_id = 'CH013160';
UPDATE characters SET role = 'SUPPORTING', favourites = 3 WHERE character_id = 'CH013165';
UPDATE characters SET role = 'MAIN', favourites = 194 WHERE character_id = 'CH013159';
UPDATE characters SET role = 'MAIN', favourites = 15 WHERE character_id = 'CH013166';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013168';
UPDATE characters SET role = 'MAIN', favourites = 66 WHERE character_id = 'CH013167';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH013169';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013182';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013173';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013178';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013175';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013179';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013176';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013180';
UPDATE characters SET role = 'MAIN', favourites = 11 WHERE character_id = 'CH013170';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH013171';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013174';
UPDATE characters SET role = 'MAIN', favourites = 13 WHERE character_id = 'CH013172';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013177';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013181';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013186';
UPDATE characters SET role = 'MAIN', favourites = 9 WHERE character_id = 'CH013184';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013190';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013188';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013189';
UPDATE characters SET role = 'MAIN', favourites = 6 WHERE character_id = 'CH013185';
UPDATE characters SET role = 'MAIN', favourites = 4 WHERE character_id = 'CH013183';
UPDATE characters SET role = 'SUPPORTING', favourites = 5 WHERE character_id = 'CH013187';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013195';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013200';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013199';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013194';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013201';
UPDATE characters SET role = 'MAIN', favourites = 7 WHERE character_id = 'CH013191';
UPDATE characters SET role = 'MAIN', favourites = 0 WHERE character_id = 'CH013192';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013196';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013193';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013198';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013197';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013209';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013204';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013206';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013208';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013211';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013210';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013203';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013212';
UPDATE characters SET role = 'MAIN', favourites = 14 WHERE character_id = 'CH013202';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013205';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013207';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013218';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013232';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013230';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013216';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013229';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013227';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013226';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013225';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013219';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013220';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013222';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013221';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH013215';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013231';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013233';
UPDATE characters SET role = 'MAIN', favourites = 0 WHERE character_id = 'CH013213';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013224';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013223';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013228';
UPDATE characters SET role = 'MAIN', favourites = 1 WHERE character_id = 'CH013214';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013217';
UPDATE characters SET favourites = 102 WHERE character_id = 'CH004063';
UPDATE characters SET favourites = 98 WHERE character_id = 'CH004082';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013244';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013239';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013238';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013242';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013237';
UPDATE characters SET role = 'MAIN', favourites = 6 WHERE character_id = 'CH013236';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH013235';
UPDATE characters SET role = 'MAIN', favourites = 11 WHERE character_id = 'CH013234';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013243';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013241';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013240';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013280';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013278';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013279';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013276';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013274';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013275';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013282';
UPDATE characters SET role = 'MAIN', favourites = 15 WHERE character_id = 'CH013272';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013281';
UPDATE characters SET role = 'MAIN', favourites = 20 WHERE character_id = 'CH013273';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013277';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013284';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013287';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013285';
UPDATE characters SET role = 'SUPPORTING', favourites = 6 WHERE character_id = 'CH013286';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013283';
UPDATE characters SET favourites = 4 WHERE character_id = 'CH004107';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013294';
UPDATE characters SET role = 'MAIN', favourites = 92 WHERE character_id = 'CH013291';
UPDATE characters SET role = 'SUPPORTING', favourites = 4 WHERE character_id = 'CH013296';
UPDATE characters SET role = 'MAIN', favourites = 427 WHERE character_id = 'CH013290';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013293';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH013289';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013295';
UPDATE characters SET role = 'MAIN', favourites = 6 WHERE character_id = 'CH013292';
UPDATE characters SET role = 'SUPPORTING', favourites = 2 WHERE character_id = 'CH013297';
UPDATE characters SET role = 'MAIN', favourites = 558 WHERE character_id = 'CH013288';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013298';
UPDATE characters SET favourites = 177 WHERE character_id = 'CH004126';
UPDATE characters SET favourites = 49 WHERE character_id = 'CH004131';
UPDATE characters SET favourites = 0 WHERE character_id = 'CH004148';
UPDATE characters SET favourites = 5 WHERE character_id = 'CH004145';
UPDATE characters SET favourites = 2 WHERE character_id = 'CH004143';
UPDATE characters SET favourites = 27 WHERE character_id = 'CH004137';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013302';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013301';
UPDATE characters SET role = 'MAIN', favourites = 13 WHERE character_id = 'CH013300';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013303';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH013299';
UPDATE characters SET favourites = 1 WHERE character_id = 'CH004173';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013309';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013312';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013313';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013308';
UPDATE characters SET role = 'MAIN', favourites = 4 WHERE character_id = 'CH013304';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013314';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013315';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013306';
UPDATE characters SET role = 'MAIN', favourites = 2 WHERE character_id = 'CH013305';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013307';
UPDATE characters SET role = 'SUPPORTING', favourites = 1 WHERE character_id = 'CH013310';
UPDATE characters SET role = 'SUPPORTING', favourites = 0 WHERE character_id = 'CH013311';