-- 翻訳済み説明文 UPDATE
-- 生成日時: 2026-07-16T17:05:33.342Z

UPDATE characters SET description = 'この物語の主人公。シリーズ開始時点でまだ15歳に過ぎないユリは、自信に満ちており、どんな慈善活動にも積極的に取り組む。彼女は当時のどの女性よりもはるかに豊富な知識を持っており、' WHERE character_id = 'CH013257';
UPDATE characters SET description = 'カメハメ王子は、ゆでたまごの漫画およびアニメシリーズ『キン肉マン』に登場するキャラクターである。4Kids Entertainmentによる『Ultimate Muscle』の翻訳版では、「プリンス・ルー・オー」と改名された。キン肉マンは彼を' WHERE character_id = 'CH006795';
UPDATE characters SET description = 'ミートは、惑星キンニク出身のチュラスコ族の一員であり、惑星全体の利益のために、父のミンチからキンニク族のマユミ・キンニクに託された。その後、ミートは地球へ送り出され、……を回収するために' WHERE character_id = 'CH006781';
UPDATE characters SET description = 'ウルフマンは、かつて「超人相撲」の横綱の座に就いていたが、後に「超人レスリング」に転向した日本の超人相撲選手である。彼は筋肉を徹底的に鍛え上げ、「美しき筋肉」を自慢している。' WHERE character_id = 'CH006820';
UPDATE characters SET description = '身長：201cm（6''6"） 分類：悪魔超人 出身地：バミューダ・トライアングル 超人指数：2,000,000 得意技：ブラックホール吸収、影の移動 タッグチーム：4Dキラーコンボ（ペン' WHERE character_id = 'CH006796';
UPDATE characters SET description = 'バッファローマンは、突進する雄牛をモチーフにした超人で、「強大かつ残忍すぎる」として宇宙の果てへ追放されたと言われる「七つの悪魔超人」の一人である。彼は非常に巨体で、2本の湾曲した' WHERE character_id = 'CH006814';
UPDATE characters SET description = '彼女は、ムギノ・シズリが率いるITEMのメンバーである。  ~!第15巻でシズリがシアーゲ・ハマズラに敗れた後、第19巻で彼女はそのリーダーとなる。!~  強力なサイキッカーであるにもかかわらず、' WHERE character_id = 'CH013585';
UPDATE characters SET description = '身長：133 cm (4''4½") 職業：死神（ヴィゾアード）；第12部隊副隊長（元）  猿垣ひよりは、引船桐生および浦鬼介が隊長を務める第12部隊の元副隊長である。' WHERE character_id = 'CH007036';
UPDATE characters SET description = 'ネリエル・トゥ・オーダーシュヴァンク、通称ネル・トゥは、初登場時には気さくで子供のような性格のアランカルである。彼女のホロウの仮面の残骸が、頭頂部に漫画風の髑髏を形作っている。ネルと' WHERE character_id = 'CH007031';
UPDATE characters SET description = '型破りな風貌のガンジュは、ベスト、スカーフ、バンダナ、そしてゴーグルを身につけている。彼はよく、皆が大きなイノシシに乗っている仲間たちと一緒にいる姿が見られる。ガンジュのイノシシの名前はボニー（愛称で' WHERE character_id = 'CH007029';
UPDATE characters SET description = '彼はアフロヘアの死神で、ほぼオマケの章にのみ登場する。朽木ルキアが死刑判決を受けた後、彼女の代わりに空洞から空倉町を守る任務に就く。空倉町で活動中' WHERE character_id = 'CH007035';
UPDATE characters SET description = '身長：151 cm（4''11"） 階級：第5師団中尉　雛森は明るく気さくな性格で、出会うほとんどの人とすぐに打ち解ける。雛森は基本的に人を信じやすいが、一方で非常に' WHERE character_id = 'CH007025';
UPDATE characters SET description = '人物像： 瀬田宗次郎は、獅子尾誠の右腕であり、獅子尾自身によって鍛え上げられた十代の暗殺者である。宗次郎は「剣気」、つまり感情の欠如で知られている。彼には怒りといった感情がなく、' WHERE character_id = 'CH007480';
UPDATE characters SET description = '斎藤一は、実在の新選組第三隊長をモデルにしています。明治時代、彼は藤田五郎という名で警察官として暮らしていました。『るろうに剣心』シリーズでは、彼は' WHERE character_id = 'CH007491';
UPDATE characters SET description = '身長：158 cm    緋村剣心は、アニメシリーズ『るろうに剣心』の主人公であり、作中では「人斬り抜刀斎」や「抜刀斎・緋村」としても知られている。彼の出自は……' WHERE character_id = 'CH007463';
UPDATE characters SET description = '身長：301 cm (9''10½") 所属：～！麦わら海賊団（現）；サン海賊団（元）；ビッグ・マム海賊団の同盟者（元）；七武海（元）； 竜宮王国（辞任）；インペルダウン（元）]!~ P' WHERE character_id = 'CH007803';
UPDATE characters SET description = '「食文化研究クラブ」の創設メンバー3人のうちの1人である1年生。クラブの中で最も背が低く、学生課への設立申請書および修正申請書の作成を担当した。' WHERE character_id = 'CH009380';
UPDATE characters SET description = '六つ子の長男でありリーダーであると同時に、グループの中で最も戦闘能力が高い。1993年の単発エピソード『おそ松くん、大人になる』では、典型的なサラリーマンとなり、未婚のままである。彼の名前は' WHERE character_id = 'CH010563';
UPDATE characters SET description = 'イヤミは、フランス出身だと自称する、とても派手でいたずら好きな男だ。彼の最も特徴的な点は、3本の大きな出っ歯、細い口ひげ、そしてビートルズ風の髪型である。彼は自分自身を' WHERE character_id = 'CH010570';
UPDATE characters SET description = '六つ子のライバル。身長はすごく低いけれど、彼らと同じ年齢だ。彼の最も特徴的なのは、大きくて丸い目と、ハゲた頭の上にある一本の髪の毛だ。彼の好きな食べ物は' WHERE character_id = 'CH010568';
UPDATE characters SET description = '生年：996年　トルフィンは、亡き父から受け継いだ一対の双剣を携えた勇敢な若者である。彼は、妥当な報酬を提示してくれる相手なら誰からでも仕事を引き受ける冷酷な傭兵団のリーダー、アスケラッドと共に旅をしている。 さらに、アスケラッドはトルフィンの父・トースを殺した張本人であり、トルフィンがアスケラッドと共に旅をしている唯一の理由は、決闘で彼を打ち負かし、父の誇りを取り戻すためである。トルフィンが望んでいるのは、ただ父の誇りを取り戻すことだけだ。' WHERE character_id = 'CH014069';
UPDATE characters SET description = 'エイナーはイングランド北部出身の男性で、奴隷として売られてしまった。彼はデンマークにたどり着き、そこでトルフィンと出会う。エイナーはトルフィンと共に、主人から二人に貸与された土地を耕作することで、奴隷の身から抜け出そうと奮闘している。' WHERE character_id = 'CH014070';
UPDATE characters SET description = 'スヴェルケルはケティルの年老いた父親で、デンマークのユトランド半島にある息子の農場の敷地内で暮らしている。' WHERE character_id = 'CH014071';
UPDATE characters SET description = 'ケティルの農場で農作業の手伝いをしている元奴隷。' WHERE character_id = 'CH014072';
UPDATE characters SET description = 'クヌートの首席家臣であり、彼の武術の師範でもあった。' WHERE character_id = 'CH014074';
UPDATE characters SET description = '「バグ・アイズ」というあだ名で知られるトーフィンは、レイフ・エリクソンと共に活動する商人である。元奴隷だったバグ・アイズは、レイフが彼をトールの息子トーフィンだと誤って思い込み、買い取ったのである。' WHERE character_id = 'CH014075';
UPDATE characters SET description = '生年：965年' WHERE character_id = 'CH014077';
UPDATE characters SET description = '彼はラグナーの兄弟だ。' WHERE character_id = 'CH014078';
UPDATE characters SET description = 'ケティルの妻。' WHERE character_id = 'CH014079';
UPDATE characters SET description = 'スヴェイン王の娘であり、ハーラルドとクヌートの妹。' WHERE character_id = 'CH014080';
UPDATE characters SET description = 'クヌートの専属護衛を務める兵士。' WHERE character_id = 'CH014083';
UPDATE characters SET description = 'ケティルの奴隷の一人で、彼の専属の侍女兼側室を務めている。アルンハイドは親切で勤勉、誠実な性格であり、トラブルを起こさずに奴隷としての生活を乗り切ろうと最善を尽くしている。' WHERE character_id = 'CH014084';
UPDATE characters SET description = 'トルケルはヨムスヴァイキングの将軍であり、ヨムスヴァイキングの首長の弟である。戦いを愛する巨漢のトルケルは、同胞のヴァイキングと戦うことこそがより大きな挑戦になると考え、デンマーク軍から離反してイングランドの傭兵となった。 この戦いを愛する心こそが、彼をカンヌート王子のデンマーク王位継承への支持へと駆り立てる。トールクェルが離反する前は、彼と共に戦い、深く尊敬しており、本編ではその息子トルフィンにも親しみを抱いている。彼はトルフィンと二度、決闘を繰り広げる。' WHERE character_id = 'CH014085';
UPDATE characters SET description = 'アスケラッドは、小規模ながらも強力なヴァイキングの一団の指揮官であり、その成功はアスケラッドの並外れた知略によるものであった。『ヴィンランド・サガ』の本編より10年前、アスケラッドはトルフィンの父であるトースを暗殺するという依頼を引き受けた。 イングランドへのヴァイキングの侵攻と戦争の最中、彼はトルフィンが自分に対して抱く復讐心を巧みに利用し、才能ある若き戦士を自分の配下に留めておいた。アスケラッドは本作において最も腕の立つ戦士の一人であり、特に' WHERE character_id = 'CH014086';
UPDATE characters SET description = 'スヴェイン王の長男であり、クヌートおよびエストリッドの兄弟。' WHERE character_id = 'CH014087';
UPDATE characters SET description = 'クヌート王の使者。' WHERE character_id = 'CH014088';
UPDATE characters SET description = '彼女はトルフィンの姉である。トルフィンが父トルスの仇を討つために旅立った後、彼女は家事をこなし、母の世話をしている。' WHERE character_id = 'CH014090';
UPDATE characters SET description = '生年：996年　クヌートはデンマークの王子である。当初、彼は臆病で女々しい性格として描かれており、美少年のような外見を持ち、家臣のラグナルがいなければまともに振る舞えない。こうした特徴に加え、彼の強いキリスト教信仰も相まって、共に働くヴァイキングたちから嘲笑の的となっている。' WHERE character_id = 'CH014091';
UPDATE characters SET description = 'アイナーの妹。' WHERE character_id = 'CH014092';
UPDATE characters SET description = 'イングランドとウェールズのほぼ全土を征服しつつ、北方の領土の支配権も維持し続けたデンマーク王。クヌートの父。' WHERE character_id = 'CH014093';
UPDATE characters SET description = 'ビョルンはアスケラッドの副官であり、戦闘そのものを愛して戦う屈強な男だ。彼はバーサーカーであり、特定のキノコを摂取することで、凄まじい狂乱状態に入ることができる。' WHERE character_id = 'CH014095';
UPDATE characters SET description = 'トースは、その驚異的な戦闘能力から「ヨムのトロール」という異名を持つヨムスヴァイキングの将軍、トルフィンの父である。トースは子供たちが生まれた後、戦いに疲れを感じ、自らの死を偽装して戦線を離れ、平和を愛する農夫として暮らすようになった。  トースは、アスケラッドやトルケルといった強敵を一騎打ちで打ち負かしたことから、本作に登場する最強の戦士と広く見なされている。その強さは際立っており、フロキでさえ、部隊を率いていても彼と直接対決することを躊躇したほどであった。' WHERE character_id = 'CH014096';
UPDATE characters SET description = '彼はクヌート王子の首席顧問である。ラグナルは、頭の両脇に生えている非常に長く、黒く、縮れた髪を除けば、頭は禿げている。深くくぼんだ目のすぐ上に、非常に太く黒い眉毛がある。また、特に頬や、濃いひげのすぐ上の部分には、非常に深いしわがある。  （出典：ヴィンランド・サーガ Wiki）' WHERE character_id = 'CH014097';
UPDATE characters SET description = 'レイフの旅の仲間。' WHERE character_id = 'CH014098';
UPDATE characters SET description = 'かつてはヴァイキングの戦士だったが、後に奴隷となった。' WHERE character_id = 'CH014099';
UPDATE characters SET description = 'ケティルに雇われたスネークの傭兵団の一員。' WHERE character_id = 'CH014100';
UPDATE characters SET description = 'スネークの「ゲスト」の一員。' WHERE character_id = 'CH014103';
UPDATE characters SET description = 'アリは、アイスランドのトルフィンが住む村の出身です。' WHERE character_id = 'CH014104';
UPDATE characters SET description = '彼女はトルフィンとイルヴァの母であり、トースの妻である。' WHERE character_id = 'CH014105';
UPDATE characters SET description = '親族：<a href="https://anilist.co/character/89509/Akemi-Aizawa">アケミ</a> （母）、<a href="https://anilist.co/character/89510/Gorou-Aizawa">ゴロウ</a>（父）  トモは、おてんばな性格で格闘技に抜群の才能を持ち、幼なじみの<a href="https://anilist.co/character/89182/Junichirou-Kubota">ジュンイチロウ</a>の心を射止めたいと切に願っている女子高生だ。 運動能力の高さにもかかわらず、彼女は自分の男っぽいところについてコンプレックスを抱いており、b' WHERE character_id = 'CH014106';
UPDATE characters SET description = '親族：<a href="https://anilist.co/character/187792/Misaki-Gundou">ミサキ</a>（母）  軍堂ミズズは『トモちゃんは女の子！』の第三の主人公である。 彼女は <a href="https://anilist.co/character/89181/相沢トモ">トモ</a>と<a href="https://anilist.co/character/89182/Junichirou-Kubota">ジュン</a>の幼なじみであり、同級生です。 彼女は狡猾で、時にはサディスティックな一面もあり、よくジュンをからかう。しかし、彼女は友人を大切にする一面もあり、トモとジュンの関係が進展することを嫌っている。' WHERE character_id = 'CH014107';
UPDATE characters SET description = '親族：<a href="https://anilist.co/character/187795/Ferris-Olston">フェリス</a> （母）、<a href="https://anilist.co/character/89511/Kousuke-Misaki">コウスケ</a> （遠縁のいとこ）　キャロルは、<a href="https://anilist.co/character/89181/Tomo-Aizawa">トモ</a>、 <a href="https://anilist.co/character/89182/Junichirou-Kubota">ジュン</a>、そして<a href="https://anilist.co/character/89183/Misuzu-Gundou">ミズズ</a>の同級生であり友人です。 英国出身の、人形のような顔立ちの美しい学生で、物事をありのままに表現するタイプです。' WHERE character_id = 'CH014108';
UPDATE characters SET description = '久保田淳一郎は、『トモちゃんは女の子！』の第二の主人公である。 彼は<a href="https://anilist.co/character/89181/Tomo-Aizawa">トモ</a>の隣人であり、幼なじみ、道場の仲間、そして高校の同級生である。ハンサムだが、トモが自分に好意を抱いていることに気づいていない。 彼はトモの父親が経営する道場で定期的に稽古をしており、トモが他の男子に気を配っていると嫉妬してしまう。  <div rel="spoiler">彼は<a href="https://anilist.co/character/89183/Misuzu-Gundou">ミズズ</a>とは仲が悪く、' WHERE character_id = 'CH014109';
UPDATE characters SET description = '三船は当初、親友の小川と同様にあまりいい人とは言えなかった。彼女は相沢トモに喧嘩を仕掛けようとしたが、それは賢明な判断ではなかった。しかし、それは誤解だったため、それ以来、二人はある程度仲良くなった。' WHERE character_id = 'CH014110';
UPDATE characters SET description = 'トモのお母さん。' WHERE character_id = 'CH014111';
UPDATE characters SET description = '彼女はキャロルの母親であり、エディ・オルストンの妻である。フェリスは娘と同じように、おっちょこちょいで軽薄な性格だ。自宅の正門から家に戻ろうとして、道に迷ってしまったことさえある。彼女はイギリスで母親が経営するカフェでウェイトレスとして働き、わずか13歳の時にエディと出会った。' WHERE character_id = 'CH014112';
UPDATE characters SET description = '彼女はミズズの母親です。' WHERE character_id = 'CH014113';
UPDATE characters SET description = '2年生で、空手部のキャプテン。キャロルのいとこであり、幼なじみでもある。彼もイギリス系の血を引いている。トモを心から尊敬している。' WHERE character_id = 'CH014114';
UPDATE characters SET description = '田辺竜美は、ジュンの同級生であり友人だ。彼は、ミズズに「トモに近づかないで」と言われた際、彼女から睨みつけられて以来、彼女に恋心を抱くようになった。' WHERE character_id = 'CH014116';
UPDATE characters SET description = 'トモの父親。相沢道場を経営しており、トモとジュンの両方を指導してきた。' WHERE character_id = 'CH014117';
UPDATE characters SET description = '小川はトモの同級生であり、三船の親友だ。' WHERE character_id = 'CH014118';
UPDATE characters SET description = 'ハンサムで、頭が良くて、優しい男の子。彼は学年で一番人気があり、よく「プリンス」と呼ばれている。成績も優秀で、多くの女子から注目を集めている。' WHERE character_id = 'CH014119';
UPDATE characters SET description = '椎名真昼の母親。' WHERE character_id = 'CH014120';
UPDATE characters SET description = '第1部隊の隊長であり、東京マンジギャングの創設者の一人。バジは荒々しい性格の持ち主だ。アドレナリンが湧き上がるスリルをこよなく愛しており、マイキー自身も「彼は特に理由もなく、ただ気分で通りすがりの人を殴り飛ばすような男だ」と語っている。戦闘中も、彼のトレードマークであるニヤリとした笑みを絶やさない。' WHERE character_id = 'CH014121';
UPDATE characters SET description = '柴泰寿の妹であり、柴八海の上の姉である。' WHERE character_id = 'CH014123';
UPDATE characters SET description = 'ヒナタとナオトの母親。' WHERE character_id = 'CH014124';
UPDATE characters SET description = '彼は東京マンジギャングの創設メンバーの一人であり、同ギャングの元第3分隊長である。' WHERE character_id = 'CH014125';
UPDATE characters SET description = '彼女は三ツ矢隆の妹であり、三ツ矢マナの姉である。' WHERE character_id = 'CH014126';
UPDATE characters SET description = '立花ヒナタと立花ナオトの父親。' WHERE character_id = 'CH014127';
UPDATE characters SET description = '長年にわたる孤独のせいで、イザナは冷酷で残忍な人物となってしまった。精神的に不安定になっただけでなく、絶対的な権力を手に入れようと躍起になっている。イザナは、第8代ブラックドラゴンズの元リーダーであり、天竺の元会長でもある。彼は「天竺編」の主要な敵役の一人である。' WHERE character_id = 'CH014128';
UPDATE characters SET description = 'キサキは『東京リベンジャーズ』の主要な敵役である。特に、トーマンの頂点へと猛スピードで駆け上がったことで知られている。   木崎は冷酷で狡猾、野心家であり、目標を達成するためなら手段を選ばない。体格は平均的だが、恐怖によって支配するその力は、自分より強い者さえも従わせる。物語全体を通じた彼の行動は、すべて東京で最も強力かつ影響力のある犯罪者になることを目指して展開される。' WHERE character_id = 'CH014129';
UPDATE characters SET description = '東京マンジギャングの創設者の一人であり、かつてヴァルハラのナンバー3を務めた。カズトラは心に深い傷を抱えている。幼い頃、家庭内暴力の渦中で、母親と父親のどちらかを選ばざるを得なかったのだ。家族というものが根本的に存在しなかったため、彼は他の幸せな家族を軽蔑するようになった。 子供たちが親と仲睦まじく過ごす姿を見るといった、ごく些細な出来事さえも、カズトラの心の傷を刺激し、彼を深く苛立たせた。' WHERE character_id = 'CH014130';
UPDATE characters SET description = 'イヌピの姉。' WHERE character_id = 'CH014131';
UPDATE characters SET description = '「ブラックドラゴン」の第10代リーダーであり、ハッカイとユズハの兄。  タイジュは残忍で暴力的だ。敵を苦しめることを楽しみ、他人の安否にはほとんど関心を示さない。実の兄弟姉妹でさえ例外ではない。相手が誰であろうと、性別を問わず構わない。カトリック教徒であり、背中には十字架のタトゥーを入れている。' WHERE character_id = 'CH014132';
UPDATE characters SET description = 'エルドメイド・ディティジョンの部下' WHERE character_id = 'CH014133';
UPDATE characters SET description = '種族：精霊　職業：教師　「教育の大樹」に関する噂や伝承から生まれた精霊であり、学校そのものを体現する存在である。エニユニエンは、その高さがどこまでも続き、雲を突き抜け、まるで天を貫きそうなほどにそびえ立つ大樹である。 エニユニエンの内部には、彼が生徒たちに教えるために使える教室がある。' WHERE character_id = 'CH014134';
UPDATE characters SET description = 'アノスによって生み出された「七大古妖帝」の一人。' WHERE character_id = 'CH014135';
UPDATE characters SET description = '2000年前の悪魔。アノスの配下の中では、シン・レグリアに次ぐ、2番目に腕の立つ剣士とされている。' WHERE character_id = 'CH014136';
UPDATE characters SET description = '「緋色の記念碑」の王、ギリシリス・デロの配下。' WHERE character_id = 'CH014137';
UPDATE characters SET description = '種族：悪魔　四悪王の一人で、「緋色の記念碑王」として知られる。' WHERE character_id = 'CH014138';
UPDATE characters SET description = 'アノスによって生み出された「七大古妖帝」の一人。' WHERE character_id = 'CH014139';
UPDATE characters SET description = 'アノスのクラスの生徒。' WHERE character_id = 'CH014140';
UPDATE characters SET description = 'カノンはアノスと戦う英雄である。彼はアノスと互いに敬意を抱いており、二人は互いを理解し合っているようだ。アノスがカノンに倒される前、アノスは「もし2000年後に再会することがあれば、友達になれたらいいのに」と願っていた。' WHERE character_id = 'CH014141';
UPDATE characters SET description = '魔王学園の生徒であり、「カオス世代」の一人。冥界王エゲス・コードの配下である。' WHERE character_id = 'CH014142';
UPDATE characters SET description = 'アノスによって生み出された「七大魔帝」の一人であり、ネクロン家の当主でもある。' WHERE character_id = 'CH014146';
UPDATE characters SET description = 'アノスによって生み出された「七大魔帝」の一人。' WHERE character_id = 'CH014147';
UPDATE characters SET description = '天の父、秩序を創り出す神、そして神々の父。' WHERE character_id = 'CH014148';
UPDATE characters SET description = 'ガイオス・アンゼムは、アノス・ヴォルディゴードによって生み出された「七人の古の魔帝」の一人である。' WHERE character_id = 'CH014149';
UPDATE characters SET description = '魔王学園の生徒であり、「カオス世代」の一員。' WHERE character_id = 'CH014150';
UPDATE characters SET description = '種族：精霊　職業：情報仲介者　記憶を失った精霊。' WHERE character_id = 'CH014151';
UPDATE characters SET description = 'イドール・アンゼオは、アノス・ヴォルディゴードによって生み出された「七大古の魔帝」の一人である。' WHERE character_id = 'CH014152';
UPDATE characters SET description = 'ミデヘイズの街を支配する魔王であり、クルートとエミリアの父でもある。' WHERE character_id = 'CH014153';
UPDATE characters SET description = 'Instagram　カズキは、同僚であり親友でもあるレイと暮らしており、レイはカズキの身の回りの世話もしている。レイとの主な仕事は、契約の締結、事前の情報収集、そして実行計画の立案である。彼は女性とギャンブルが好きで、コミュニケーション能力にも長けている。料理や掃除も得意で、時折、レイの放漫な生活態度を叱ることもある。   かつては結婚しており、妻は彼の子供を身ごもっていたが、怪しげな仕事が原因で彼女を失ってしまった。' WHERE character_id = 'CH014154';
UPDATE characters SET description = 'レイは口数の少ない男で、カズキがすでに自分の家に居候していることにも特に気にしていない。体力が強く、戦闘能力や射撃の腕前は業界でもトップクラスだ。仕事と私生活をきっちりと区切っており、ほとんどの時間を家でビデオゲームをして過ごしている。 彼の家族は巨大な裏社会の一族であり、両親は彼が幼い頃から、才能ある暗殺者として彼を鍛えてきた。彼は一族間の抗争から逃れることができず、' WHERE character_id = 'CH014155';
UPDATE characters SET description = 'ミリは、無邪気で、元気いっぱいで、何事にもひるまない少女だ。彼女の父親はマフィアのボスであり、人身売買組織の主要な仲介人でもある。母親は、そのボスの愛人だ。 父親を探してホテルに到着した彼女は、銃撃戦に巻き込まれるが、カズキに助けられる。彼女は人懐っこく、カズキを「パパ・カズキ」、レイを「パパ・レイ」と呼んでいる。' WHERE character_id = 'CH014156';
UPDATE characters SET description = '親族：諏訪レイ（息子）' WHERE character_id = 'CH014157';
UPDATE characters SET description = 'レイとカズキに仕事と情報の両方を提供しているカフェのオーナー。' WHERE character_id = 'CH014160';
UPDATE characters SET description = '「あおぞら保育園」の保育士。' WHERE character_id = 'CH014162';
UPDATE characters SET description = '人身売買組織の主要な仲介者。' WHERE character_id = 'CH014165';
UPDATE characters SET description = 'カズキの妊娠中の妻。' WHERE character_id = 'CH014166';
UPDATE characters SET description = 'ユズコの妹であり、カズキの義妹。' WHERE character_id = 'CH014168';
UPDATE characters SET description = 'ミリの母親。マフィアのボスである早見篤と不倫関係を持った後、シングルマザーとして出産した。' WHERE character_id = 'CH014170';
UPDATE characters SET description = 'タイプ：機械生命体　謎めいた、唯一無二の存在。機械生命体であるにもかかわらず、その外見はアンドロイドに酷似している。' WHERE character_id = 'CH014172';
UPDATE characters SET description = 'ワタは、Androidのレジスタンスキャンプのメンバーです。' WHERE character_id = 'CH014173';
UPDATE characters SET description = '中学時代のキメン組の担任（高校時代はコジョウ組の担任）。美人で、ユーモアたっぷりの国語の先生だ。     キメン組の' WHERE character_id = 'CH012123';
UPDATE characters SET description = 'タイプ：機械生命体　謎めいた、唯一無二の存在。機械生命体であるにもかかわらず、その外見はアンドロイドに酷似している。' WHERE character_id = 'CH014174';
UPDATE characters SET description = 'キンは、Androidのレジスタンス・キャンプの一員である。' WHERE character_id = 'CH014175';
UPDATE characters SET description = '「ウェポン・トレーダー」は、Androidのレジスタンス・キャンプのメンバーです。' WHERE character_id = 'CH014176';
UPDATE characters SET description = 'Supply Traderは、Androidのレジスタンス・キャンプのメンバーです。' WHERE character_id = 'CH014177';
UPDATE characters SET description = 'タイプ：機械生命体　すべての機械生命体を結びつける「機械ネットワーク」から切り離された、穏やかな物腰と優しい性格を持つ機械生命体。幅広い知識を持ち、志を同じくする他の機械生命体たちと共に暮らす独自のコミュニティを築き上げた。' WHERE character_id = 'CH014178';
UPDATE characters SET description = 'フーリガンたちを統率する武装探偵社の社長。普段は表に出ることは少ないが、決定的な局面では威風堂々と指揮を執る。幸一は威厳と地位を兼ね備えた人物であるため、軽薄な蘭ポでさえ、彼の命令があれば実際に働くようだ。  （出典：文豪ストレイドッグス ウィキ）' WHERE character_id = 'CH014189';
UPDATE characters SET description = '能力：月明かりの下の獣　人喰い虎に襲われた貧しい孤児院から追い出され、横浜へとやって来た。 飢え死にしそうな状況で、彼は太宰と出会い、探偵事務所の手伝いをする仕事を得た。これまで友人や家族を持ったことがなく、「役立たず」というレッテルを貼られてきたため、彼は自信に欠けている。' WHERE character_id = 'CH014190';
UPDATE characters SET description = '家族構成～！　父：グンター　母：エファ　姉：トゥーリ　弟：カミル！～　身分　階級：平民　職業：軍人の子　<br>貧しい平民の家の末娘' WHERE character_id = 'CH012550';
UPDATE characters SET description = '武装探偵社の名探偵。 同僚からも認められる鋭い観察力を持ち、警察からの依頼を受けて難事件を解決している。自信家なため、物言いは大胆で子供っぽい。モットーは「僕に任せてくれれば、すべてうまくいく！」。論理的な思考と空想的な物語が好きだ。' WHERE character_id = 'CH014191';
UPDATE characters SET description = '能力：もはや人間ではない　武装探偵社のメンバー。死ぬ場所を探し求める自殺マニアである。 しかし、痛みは嫌いで、できれば美しい女性との恋人の自殺を望んでいる。目的意識がなく、捉えどころがなく、無頓着で、普段は冗談を飛ばしているが、本気になると、洞察力に富み知性的な人物であることが明らかになる。同僚の国木田をからかうのが大好きだ。' WHERE character_id = 'CH014192';
UPDATE characters SET description = '能力：オーバーコート　ニコライ・ゴーゴリは「デケイ・オブ・エンジェルズ」の一員である。彼は言葉で人々に見せ物をすることを楽しむサディストだ。彼は風変わりで、活力に満ち、反省の色を見せず、極めて謎めいた人物である。しかし、ゴーゴリ自身は、その奇抜なイメージが真実であるかもしれないし、そうでないかもしれないと示唆している。 他人を殺害することに対して何の後悔も抱かない彼の側面も、罪悪感を抱き、自らの行為が不当かつ残酷であることを十分に自覚している側面と同様に、本物なのだ。彼は、自分が常に求めてきたものを体験するために、「デケイ・オブ・エンジェルズ」に加わった。' WHERE character_id = 'CH014193';
UPDATE characters SET description = '能力：「モルグ街の黒猫」　ペットのアライグマ、カールを常に連れ歩いているギルドのメンバー。ポーの能力「モルグ街の黒猫」は、誰かをその人が読んでいる物語の中へと送り込むことができる。 ポーは内気だが意志が強い人物として描かれている。彼は蘭ポを倒すための計画を6年間も練り続けており、自分が大切に思うことには懸命に取り組む姿勢を見せている。彼はしばしば、他人が聞き取れないほど小さな声で話す。' WHERE character_id = 'CH014194';
UPDATE characters SET description = '能力：退廃論　ポート・マフィアの元専属情報員。内務省特殊能力局でカウンセラー補佐として勤務している。  概して、安吾は落ち着きがあり、穏やかな青年で、太宰治よりも自制心が強く、織田作之助よりも規律正しい。彼は二人を真の友人として大切にしているが、太宰治には、彼ほど無鉄砲な行動に出ないように抑えてくれる人物が必要だと強く信じている。' WHERE character_id = 'CH014195';
UPDATE characters SET description = '「死者の館のネズミ」の一員。その能力は「パーフェクト・クライム」である。' WHERE character_id = 'CH014196';
UPDATE characters SET description = '能力：真冬の追憶　ポート・マフィア傘下の殺し屋部隊「ブラック・リザード」の指揮官。強面かつ暴力的な態度を見せているが、友人に対しては深い思いやりを持っている。銃の腕前が非常に優れており、特に二丁拳銃を操る際にはその実力を発揮する。' WHERE character_id = 'CH014197';
UPDATE characters SET description = 'シアター・ムンディで上演された舞台『生ける世界は夢、夜の夢こそが現実』の主演俳優。' WHERE character_id = 'CH014198';
UPDATE characters SET description = '中矢は、マフィアを裏切って武装探偵社に加わった太宰治を激しく憎んでいるポート・マフィアの構成員だ。また、太宰から絶えずからかわれることもあって、その憎しみはますます強まっている。 中也は小柄だが、動きが素早く、強力な格闘術を駆使する。彼の能力「For The Tainted Sorrow」は重力の操作を主軸としており、触れた物の重力を操作・変化させ、一定時間その状態を維持することができる。' WHERE character_id = 'CH014200';
UPDATE characters SET description = '能力：犯罪と罰　地下組織「死者の家のネズミ」の首領であり、テロ組織「天使の腐敗」の一員でもある。 他人に対しては冷静で自信に満ち、傲慢でありながらも礼儀正しい態度を保っており、極めて知性が高く、狡猾で陰険な一面を見せている。非常に宗教心が強く、人間の罪、特に能力者たちの罪について頻繁に語っている。彼自身の話によると、貧血を患っているという。' WHERE character_id = 'CH014201';
UPDATE characters SET description = 'シグマはテロ組織「デケイ・オブ・エンジェルズ」の一員であり、スカイ・カジノのオーナーである。その能力は不明だが、フョードルによれば「エンジェルズ」の中で最も弱いとされる。そのため、戦闘よりもサポート寄りの能力である可能性がある。  彼は客に対して非常に親切であり、自身のカジノに対して誇りと所有者としての意識を持っていることが示されている。' WHERE character_id = 'CH014202';
UPDATE characters SET description = '好きなもの：神、聖書、信仰、純潔 嫌いなもの：悪魔、異端 能力：『緋文字』　自身の血を聖なる言葉に変え、それを操る能力を持つ。' WHERE character_id = 'CH014204';
UPDATE characters SET description = '着物を着こなすおとなしいお嬢様だが、ポート・マフィアの一員でもある。殺人の能力を持つことから、組織に見出され、暗殺者として育てられた。' WHERE character_id = 'CH014205';
UPDATE characters SET description = 'ケンシロウは「北斗神拳」流派の64代目継承者である。彼の胸には、「北斗七星」の形をした7つの傷跡があり、それはシンによって刻まれたものである。彼は強靭で、概して' WHERE character_id = 'CH012843';
UPDATE characters SET description = '能力：比類なき詩人　武装探偵社のメンバー。表紙に「理想」と書かれたノートを持ち歩いており、その中には人生の指針が記されている。堅物な性格で、予定が狂うことを何よりも嫌う。 自由奔放な太宰の相棒として、彼の苦労は尽きることがない。' WHERE character_id = 'CH014206';
UPDATE characters SET description = '能力：完璧　かつてポート・マフィアの一員だった。 太田は、ダザイから「マフィアに身を置きながらも、心優しい男」と評されていた。彼は並外れて洞察力に富んでおり、ダザイを「世に疲れ果て、ただ死を待つだけの、私の親愛なる友人」と呼ぶほど、ダザイの心を誰よりも深く理解していた。' WHERE character_id = 'CH014207';
UPDATE characters SET description = '日本の警察官。かつて蘭ポが事件の捜査で共に働いた安井さんの後任。' WHERE character_id = 'CH014208';
UPDATE characters SET description = '大内福地は「ハンティング・ドッグス」特殊部隊の指揮官であり、「ミラー・ライオン」という能力を持つ。' WHERE character_id = 'CH014209';
UPDATE characters SET description = '能力：ヴィータ・セクアリス　森オウガイはポート・マフィアのボスである。オウガイは分析力に優れ、戦術的である。しばしば大げさな演技を見せるが、内心ではめったに動揺を見せない。   暴力に関しては、ある種の冷酷さと揺るぎない姿勢を見せている。しかし、殺すこと自体に特別な喜びを感じている様子は見られない。彼の冷酷さは、実利主義に根ざしている。時折威圧的で、恐ろしいほど格式ばったオーラを放つこともあるが、親しみやすいほど礼儀正しい態度を見せることも多い。' WHERE character_id = 'CH014210';
UPDATE characters SET description = 'エドガー・アラン・ポーの飼いアライグマ。' WHERE character_id = 'CH014211';
UPDATE characters SET description = 'テルコは「ハンティング・ドッグス」特殊部隊の副司令官であり、「魂の息吹」という能力を持っている。' WHERE character_id = 'CH014212';
UPDATE characters SET description = '能力：小雪　武装探偵社のメンバーであり、ナオミの兄である。' WHERE character_id = 'CH014213';
UPDATE characters SET description = '「ポート・マフィア」のメンバーで、普段は森オウガイと一緒にいることがよく見られる少女。' WHERE character_id = 'CH014214';
UPDATE characters SET description = '能力：『若草物語』　ギルドの戦略家。彼女の能力は、時間を通常の1/8000の速度まで遅くすることができるが、これは彼女が個室に一人きりの時にのみ発動する。' WHERE character_id = 'CH014215';
UPDATE characters SET description = '能力：「雪中の梅」　テッチョウ・スエヒロは、「狩猟犬」特殊部隊の隊員であり、「雪中の梅」という能力を持つ。テッチョウは仲間たちよりもかなり真面目な性格だが、食の好みが風変わりなため、やはり変わり者扱いされている。 彼は「狩猟犬」としての任務を真摯に受け止め、強い正義感を持っている。拷問という行為を嫌悪し、非常に思いやりのある人物だ。  テッチョウの能力「雪中の梅」は、サイズや形状、そして' WHERE character_id = 'CH014216';
UPDATE characters SET description = '能力：雨に負けぬ男　武装探偵社のメンバー。スカウトされる前は、電気の通っていない田舎で暮らしていた。疑い深くなく、相手に関係なく理解を示し、思いやりを持って接する。「ケンちゃん」と呼ばれる友人がたくさんいる。 音楽、天ぷらそば、三ツ矢サイダーが好きだ。  （出典：文豪ストレイドッグス Wikia）' WHERE character_id = 'CH014217';
UPDATE characters SET description = '能力：「ザ・グレート・フィッツジェラルド」　フランシスは、アメリカの秘密結社「ギルド」のリーダーを名乗っている。同組織は、米国で何らかの強力な影響力を持つ、富裕層や悪名高い人物たちで構成されている。 彼の能力「ザ・グレート・フィッツジェラルド」は、莫大な財産から費やした金額に応じて、自身の能力や特性を強化することを可能にする。家族を愛する気性の激しい男であり、目標を達成するためならほぼ何でもする。' WHERE character_id = 'CH014218';
UPDATE characters SET description = '竜之介の妹であり、「ブラック・リザーズ」突撃部隊の一員。太宰とは仲が良いようだ。' WHERE character_id = 'CH014219';
UPDATE characters SET description = 'サイギク・ジョウノは「ハンティング・ドッグス」のメンバーである。彼は「プライスレス・ティアーズ」という能力を持っている。' WHERE character_id = 'CH014220';
UPDATE characters SET description = '能力：「汝、死すべからず」　ボブカットの現代的な女性で、武装探偵社のメンバー。同社にとって欠かせない優秀な医師ではあるが、同社のメンバーは皆、彼女の治療を受けることを恐れている。 彼女の前では、時代遅れの女性蔑視的な表現を使うのは控えたほうがよい。' WHERE character_id = 'CH014221';
UPDATE characters SET description = '「ギルドの同胞団」というアビリティユーザー協会のメンバー。彼女の能力は「アビスレッドのアン」として知られている。' WHERE character_id = 'CH014222';
UPDATE characters SET description = '能力：フォーリング・カメリア　ポート・マフィアの一員であり、「ブラック・リザーズ」襲撃部隊の隊長。彼の能力「フォーリング・カメリア」は、触れた物体を凄まじい勢いで後方へ吹き飛ばす。' WHERE character_id = 'CH014223';
UPDATE characters SET description = '「グラニー」という愛称で呼ばれる彼女は、他の孤児たちと共に幼いバットを育て上げた女性だ。一見、バットとは仲が良くないように見えるかもしれないが、実際には二人は互いに深く慕い合っている。彼女は掘り起こそうと試みる' WHERE character_id = 'CH012848';
UPDATE characters SET description = 'いつでもどこでも突然現れる女子高生。先輩に夢中なことが常だ。水泳部の部員らしい。長瀧は、元気でスポーツ万能、人気者で、少々サディスティックな一面もあるが、心の奥底はとても優しい女の子で、よく「サドデレ」と呼ばれる。 彼女は、友人のガモちゃん、ヨシ、サクラと共に「クールなグループ」の一員であり、水泳部の部員でもあるが、ムエタイ、ボクシング、カポエイラなどの格闘技にも興味を持っている。' WHERE character_id = 'CH014224';
UPDATE characters SET description = '高校生で美術部の部員である彼は、自作の漫画を描いたり、後輩のナガトロと知り合ってからは彼女のイラストを描いたりして楽しんでいる。放課後はほとんど毎日、ナガトロと一緒に美術部で過ごし、そこでとんでもない騒動が繰り広げられる。 彼は内向的で、落ち着きがなく、一匹狼で、オタク気質、そして内気な志望アーティストであり、他人との交流を避けようとしており、友達はいないようだ。また、長門からは「隠れ変態」と呼ばれている。' WHERE character_id = 'CH014225';
UPDATE characters SET description = '柔道代表候補の折原は、長瀞の柔道におけるライバルであり、もともと才能がなかった。' WHERE character_id = 'CH014226';
UPDATE characters SET description = '彼女は先輩の母親で、息子をとても大切に思っている優しい女性ですが、非常に多忙な仕事のため、よく家を空けています。' WHERE character_id = 'CH014228';
UPDATE characters SET description = '美術部の部長。長い髪が顔を縁取り、瞳は濃い茶色をしている。先輩とのやり取りを見る限り、性格は厳格で真面目だが、長瀧とは異なり、先輩に対しては敬意を持って接している。また、先輩が執筆したある漫画の女性キャラクターに似ている。 須ノ宮は彼女の従妹である。' WHERE character_id = 'CH014230';
UPDATE characters SET description = '彼女は高校生で、ガモちゃん、ヨシ、ナガトロ、サクラの同級生である。特にナガトロとサクラの2人とは、彼女と友人のラビちゃんがかなり親しい関係にあるようだが、その後、グループの他のメンバーとも時折一緒に過ごすようになった。彼女のフルネームは現時点では不明である。' WHERE character_id = 'CH014231';
UPDATE characters SET description = '生まれつきの天然でツインテールの女の子。ガモちゃんを好きで、いつもガモちゃんの言ったことを繰り返したり、その後に何か付け加えたりするおバカな子だ。 ヨシは、ゴリラのTシャツを着ている姿が見られたり、飼い犬を飼っていたりするなど、動物も好きなようだ。また、あるコンテストで、ナガトロから「スクイディ」のぬいぐるみを、先輩との引き換えとして受け取ったこともあることから、かわいいものも好きなようだ。' WHERE character_id = 'CH014232';
UPDATE characters SET description = '中くらいの長さの髪をしたキャラクター。人をからかうのが好きだ。' WHERE character_id = 'CH014233';
UPDATE characters SET description = '日焼けした肌と柔らかなウェーブのかかった髪をした少女。実は「ハラグロ」な性格だ。（ハラグロ：外見は親切で友好的だが、その性格を他人を操る手段として利用しているキャラクターのこと。）' WHERE character_id = 'CH014234';
UPDATE characters SET description = '彼女は高校生で、ガモちゃん、ヨシ、ナガトロ、サクラの同級生だ。特にナガトロとサクラの2人とは、彼女と友人のネコバがかなり親しい関係にあるようだが、その後、グループの他のメンバーとも時折一緒に過ごすようになった。' WHERE character_id = 'CH014235';
UPDATE characters SET description = '彼女は長瀧のお姉さんだ' WHERE character_id = 'CH014236';
UPDATE characters SET description = '彼女は、先輩が3年生の時に美術部に入部した女子高生であり、中学時代からの先輩の知人でもある。また、元美術部部長のいとこで、その部長と驚くほど容姿が似ており、人前で裸になるという癖も共通している。他の登場人物全員にとっての後輩にあたる。' WHERE character_id = 'CH014238';
UPDATE characters SET description = 'タカオは高校生であり、先輩の同級生兼友人でもある。彼はヒノとともに、先輩と3人組を結成していた。物語が進むにつれて――先輩ほど一貫してではないものの――彼は時折、長瀞のグループ、特にサクラとつるむようになった。' WHERE character_id = 'CH014239';
UPDATE characters SET description = '種族：人間　ベル・クラネルは、ヘスティア・ファミリアの隊長である。ベルは、迷宮都市オラリオの近く、山奥の田舎の農村で祖父に育てられた。祖父から英雄に関する多くの物語を聞いたり読んだりして、自分も偉大な英雄になりたいという夢を育んだ。 祖父の死後、彼は自ら村を離れ、夢を叶えるためにオラリオへと旅立った。街に到着すると、ベルはヌムに入ろうとしたが……' WHERE character_id = 'CH014240';
UPDATE characters SET description = '種族：パラム　リリルカ・アルデはヘスティア・ファミリアの一員である。元々はソーマ・ファミリアに所属していたが、ウォーゲーム終了後に自由の身となったことを機に、ヘスティア・ファミリアに転籍した。 リリはソーマ・ファミリアに所属するホビットの両親の間に生まれ、生来からファミリアの一員であった。しかし、両親は彼女の面倒を見ず、代わりに自分たちのために金を稼ぐよう命じた。 しばらくして、両親はダンジョンで命を落とし、彼女は独りで生きていくことを余儀なくされた。ソーマ・ファミリアは' WHERE character_id = 'CH014241';
UPDATE characters SET description = '種族：人間　ウェルフ・クロッツォはヘスティア・ファミリアの一員であり、ベルの専属鍛冶師である。後にヘファイストス・ファミリアから転向し、ヘスティア・ファミリア全体の鍛冶師となった。 ウェルフはもともと、アレスが統治する国家型ファミリア「ラキア」で生まれた。クロッツォ家の出身として、先祖たちが魔法剣の製作で成功を収めたおかげで、貴族として暮らしていた。しかし、スキル「クロッツォ・ブラッド」が現れた日、彼の人生は一変した。このスキルにより、彼は再び魔法剣を製作できるようになったのだ。デスピ' WHERE character_id = 'CH014242';
UPDATE characters SET description = '種族：人間　所属：ヘスティア・ファミリア・タケミカヅチ・ファミリア（一時離脱中）　レベル：2　スキル：ヤタノクロガラス・ ヤタノシロガラス 魔法：フツノミタマ 武器：コテツ • チザン • シュンサン • シャクヤ  ヤマト・ミコトは、ウォーゲーム中にヘスティア・ファミリアを支援するために転向し、現在はヘスティア・ファミリアおよびタケミカヅチ・ファミリアの所属となっている。 ミコトはもともと極東の出身である。彼女の両親は、彼女が生まれて数年後に亡くなった。ツクヨミとタケミカヅチは、その幼い少女を自分たちの孤児院に引き取り、' WHERE character_id = 'CH014243';
UPDATE characters SET description = '種族：レナード　三条のハルヒメは、ヘスティア・ファミリアの一員であり、かつてはイシュタル・ファミリアに所属していた。ハルヒメは、極東の貴族の家系に生まれ、気品あるお嬢様として育った。孤独な生活を送り、彼女の家はまるで檻のようで、友人もいなかった。 ある時、タケミカヅチ・ファミリアの子供たちが、彼らの神の許可を得て、夜になると彼女を外に連れ出し、一緒に遊ぶようになった。その後、誰かが彼女に供物を食べたという濡れ衣を着せた。これに激怒した父親は、彼女を……' WHERE character_id = 'CH014244';
UPDATE characters SET description = '種族：エルフ　リュウ・ライオンは「豊穣のホステス」でウェイトレスをしている。リュウは、故郷の森リュミルアで聖なる木を守り続けてきた一族の出身だった。 時が経つにつれ、彼女は、他の種族に対する仲間のエルフたちの振る舞いを見て、美しいエルフこそがすべての種族の中で最も醜い存在だと考えるようになった。どんなにそれを忘れようとしても、一度考え始めると、その考えは彼女の心に深く根付いてしまった。やがて、その考えは、彼女が決断を下すのに十分なほど強くなっていった。' WHERE character_id = 'CH014245';
UPDATE characters SET description = '種族：神　所属：ヘスティア・ファミリア　ヘスティアは、ベルの可能性を見出す、元気で優しい女神です。彼女は働き者で、ベルがダンジョンへ出かけている間、二人を養うために仕事をしています。 ヘスティアは、ベルに深く恋していることや、彼女たちがベルの力成長の要因となっていることから、アイズをはじめとする女の子たちがベルに興味を示すと、非常に器量が狭く、すぐに嫉妬してしまう傾向がある。ベルに対しては大人びて頼もしく見えるが、実のところヘスティアは怠け者の女神であり、彼女は……' WHERE character_id = 'CH014246';
UPDATE characters SET description = '種族：人間　身長：164 cm (5''5")　所属：ミアチ・ファミリア（過去）、アポロ・ファミリア（現在）　レベル：3　到達階：27　ステータス：• 筋力：I0 • 耐久力：I0 • 器用さ：I0 • 敏捷性：I0 • 魔力：I0 • 異常耐性： I • 脱出：？ スキル：エリオスの情熱 • ローラスの花冠 魔法：ラウムレ 装備：フェンサー・ローレイト  ダフネ・ラウロスはミアチ・ファミリアのメンバーであり、かつてはアポロ・ファミリアに所属していた。ダフネは外見とは裏腹に、冷静沈着な性格である。彼女はアポロに対して複雑な感情を抱いている' WHERE character_id = 'CH014247';
UPDATE characters SET description = '種族：人間　所属：タケミカヅチ・ファミリア　レベル：2　武器：コウゴウ　鹿島オウカは、タケミカヅチ・ファミリアの一員であり、その隊長である。 オウカは、ファミリア内で強さと尊敬を集めるメンバーである。リーダーとして、ダンジョン探索の際にはしばしばファミリアメンバーの行動方針を決定する。仲間を指揮し、絶体絶命の状況では厳しい決断を下すこともできる。その決断にもかかわらず、彼はファミリアのメンバーに対して深い思いやりを示している。それは、彼らが幼い頃から互いを知り合っているからである。' WHERE character_id = 'CH014248';
UPDATE characters SET description = '種族：人間　ルノワール・ファウストは、「豊穣のホステス」でウェイトレスとして働いている。かつてはデメテル・ファミリアの一員として「ファウスト」の通称で知られた賞金稼ぎだった。ルノワールは、帝国の領土に住んでいた両親の間に生まれた。 しかし、戦争のせいで両親は間もなく亡くなり、彼女はストリートチルドレンの一人として生きることを余儀なくされた。過酷な環境でしばらく過ごした後、ファルナの存在を知りファミリアに加入したが、その後、自身の女神が……' WHERE character_id = 'CH014249';
UPDATE characters SET description = 'ボースは、黒髪にティール色の瞳を持ち、左目を眼帯で覆った、がっしりとした筋肉質の男だ。彼は、筋肉質な体を際立たせる袖なしの開襟ジャケット、アームカバーと手袋、青いズボン、ブーツ、そして赤い怪物の顔が彫られ、毛皮があしらわれたベルトを身につけている。' WHERE character_id = 'CH014250';
UPDATE characters SET description = '種族：神　所属：フレイヤ・ファミリア　フレイヤはフレイヤ・ファミリアの頭目である。遥か昔、ヘラはゼウスの依頼を受け、世界を救うという目的のためにフレイヤに協力を求めた。フレイヤはヘラに試練を課し、勝てば協力すると告げた。 試練に敗れたフレイヤは、その取り決めに従い、オラリオに留まることを余儀なくされた。その結果、ファミリアのメンバー数名も失うこととなった。それからしばらくして、フレイヤはシルという名の少女と出会った。彼女を救い出すと約束した後、フレイヤはこう尋ねた。' WHERE character_id = 'CH014251';
UPDATE characters SET description = '種族：神　所属：ヘファイストス・ファミリア　ヘファイストスはヘファイストス・ファミリアの当主である。怠け者の女神として知られていた友人ヘスティアに比べ、ヘファイストスは厳格で勤勉な性格を示している。また、子供たちを非常に大切にしていることでも知られている。  鍛冶の女神であるヘファイストスは、その道の達人である。彼女は、アルカナムを持たない状態でも、ヘスティアのファルナを宿した生きた武器「ヘスティアのナイフ」を鍛え上げることができた。' WHERE character_id = 'CH014252';
UPDATE characters SET description = '種族：ドワーフ' WHERE character_id = 'CH014253';
UPDATE characters SET description = '種族：キャットピープル　所属：豊穣のホステス　レベル：4　アーニャ・フロメルは「豊穣のホステス」でウェイトレスをしている。1歳の時、アーニャは両親と家を失った。そのため、兄のアレンは彼女を守りながら、王国の廃墟をさまようことを余儀なくされた。 そうして2年間が過ぎた頃、彼らはフレイヤと出会った。フレイヤは二人を自分の元へ連れて行くことを提案し、二人はそれを受け入れた。アイスがオラリオに来る少し前、ミアはフレイヤ・ファミリアを一部離脱して「豊穣のホステス」を開店し、アニャを雇った。' WHERE character_id = 'CH014254';
UPDATE characters SET description = '種族：ゼノス　所属：ゼノス・ヘスティア・ファミリア・ウラノス　レベル：2+（推定）　ウィーネは、ダンジョンの中層で生まれた謎めいた女性のヴォイヴルである。後に、彼女がゼノスの一員であることが明らかになる。   ウィーネはゼノスであるため、モンスターでありながら話すことができる。彼女は心優しく、人々がモンスターを邪悪だと見なしていたにもかかわらず、ある少年を助けた。ウィーネはヘスティア・ファミリア、特にベルとハルヒメに親しみを抱くようになった。ウィーネは服を着ることを好まず、拒否して' WHERE character_id = 'CH014255';
UPDATE characters SET description = '種族：人間　所属：アポロ・ファミリア（過去）、ミアック・ファミリア（現在）　レベル：3　到達階：27　ステータス：• 筋力：I0 • 耐久力：I0 • 器用さ：I0 • 敏捷性：I0 • 魔法力：I0 • 治療力： I スキル：五次元トロイア魔法：ソウルライト • キュア・エフィアルテス 装備：聖なるクリスタルの杖 • ウサギのお守り  カサンドラ・イリオンはミアック・ファミリアのメンバーであり、かつてはアポロ・ファミリアに所属していた。 カサンドラは内気な性格で、彼女を世話しているダフネ・ラウロスと一緒にいる姿がよく見られる。ダフネと同様に' WHERE character_id = 'CH014256';
UPDATE characters SET description = '種族：エルフ' WHERE character_id = 'CH014257';
UPDATE characters SET description = '種族：キャットピープル　所属：豊穣のホステス・ニョルド・ファミリア　レベル：4　魔法：フェレス・クルス　武器：ヴィオレッタ　クロエ・ロロは、パブ「豊穣のホステス」のウェイトレスであり、かつてはニョルド・ファミリアの一員として「ロロ」の名で知られた元暗殺者である。 クロエは、犯罪組織として活動していたファミリアのメンバーである両親の間に生まれた。生まれたその瞬間から、彼女は様々な暗殺の手法を教え込まれ、それらを適切に活用すると称賛された。しかし、彼女は次第に自分の' WHERE character_id = 'CH014258';
UPDATE characters SET description = '種族：ゼノス　身長：158 cm (5''2")　所属：ゼノス・ウラノス　フィアはハーピー種のゼノスである。ゼノスであるため、フィアは通常のモンスターよりもはるかに知性が高く、強力である。' WHERE character_id = 'CH014259';
UPDATE characters SET description = '種族：アマゾネス　身長：175 cm (5''9")　所属：イシュタル・ファミリア（過去）、ヘルメス・ファミリア（現在）　レベル：4　到達階：45　ステータス：• 筋力：I11 • 耐久力：I4 • 敏捷力：I11 • 敏捷性：I6 • 魔法：I1 • ハンター：？ • 拳撃：？ • 異常耐性：？ 魔法：ヘル・カイオス 武器：グレート・ポダオ・ザガ  アイシャ・ベルカはヘルメス・ファミリアのメンバーであり、かつてはイシュタル・ファミリアの幹部を務めていた。 アイシャは頼りになる人物であり、支援すると決めた相手に対しては姉妹のような態度で接することで知られている。' WHERE character_id = 'CH014260';
UPDATE characters SET description = '種族：神　所属：ギルド • ゼノス　ウラノスはギルドの首領である。ウラノスは「統治はするが、干渉はしない」という哲学を掲げており、ギルドの運営はロイマン・マーディールに任せて、自身はギルドの下にある「祈りの間」に留まり、その神性を用いてダンジョンからモンスターが外に出るのを防いでいる。 彼は非常に冷静沈着で、1000年にわたり忍耐強くダンジョンを見守ってきた。また、新しいアイデアにも寛容であり、ゼノスが人々と平和に共存できると真っ先に信じた人物でもある。' WHERE character_id = 'CH014262';
UPDATE characters SET description = '種族：ゼノス　所属：ゼノス・ウラノス　ローラはラミア種のゼノスである。ゼノスであるローラは、通常のモンスターよりもはるかに知性が高く、力も強い。ローラは水色の鱗に覆われた肌を持ち、爪と長い蛇のような尾を備えている。' WHERE character_id = 'CH014263';
UPDATE characters SET description = '種族：神　所属：ミアチ・ファミリア　ミアチはミアチ・ファミリアの頭目である。ミアチは親切で思いやりがあり、人当たりの良い神であり、ベルやヘスティア・ファミリアのメンバーとも良好な関係を築いており、よくベルに無料でポーションを配っている。 無料でポーションを配る癖があり、それがファミリアの財政難を招いている。また、女性に対して親しみやすい態度をとるため、タケミカヅチと共に「生まれつきのプレイボーイ」と呼ばれている。さらに、自身のファミリアのメンバーであるナアザ・エリスイスを気遣い、彼女を連れて' WHERE character_id = 'CH014264';
UPDATE characters SET description = '種族：神　所属：アストラエア・ファミリア' WHERE character_id = 'CH014265';
UPDATE characters SET description = '種族：チエントロープ　身長：169 cm (5''7")　所属：ミアック・ファミリア　レベル：2　ステータス：• 筋力：G218 • 耐久力：G204 • 敏捷力：G293 • 機敏力：F339 • 魔力：H187 • 混血：I 魔法：ダルブ・ダオル  ナアザ・エリスイスは、ミアック・ファミリアの医師である。ナアザは、ミアックやヘスティアと同様に、ベル・クラネルと良好な関係を築いている。しかし、彼女のファミリアは貧しいため、ベルに粗悪な品を売りつけたり、高価な商品を買い取るよう説得したりしていた。 それでもナアザは、ベルが助けを必要とする時には手を差し伸べる。例えば、彼女がベルを助けた時のように……' WHERE character_id = 'CH014266';
UPDATE characters SET description = '種族：ゼノス　身長：167 cm (5''6")　所属：ゼノス・ウラノス　レベル：5（推定）　リッドはリザードマンのゼノスである。ゼノスであるため、リッドは通常のモンスターよりもはるかに知性が高く、強力である。 彼は最強クラスのゼノスの一人であり、一級冒険者に匹敵する実力を持つ。リッドは赤い鱗とオレンジ色の瞳をしている。全身鎧を身にまとい、シミターとロングソードを操る。  リッドは心開いていて親しみやすい性格で、初めて会ったベルにもすぐに打ち解け、彼に愛称まで付けてあげた。A' WHERE character_id = 'CH014267';
UPDATE characters SET description = '種族：神　所属：タケミカヅチ・ファミリア    タケミカヅチは神であり、タケミカヅチ・ファミリアの頭目である。 タケミカヅチはヘスティアと親しく、彼女に「土下座」など多くのことを教えてきた。ファミリアのメンバーには親切である。また、生まれつきのプレイボーイでもあり、自分の行動が周囲にどのような影響を与えるか全く気づいていないため、無神経な印象を与えてしまう。' WHERE character_id = 'CH014268';
UPDATE characters SET description = '所属：ウラノス • ゼノス 過去の所属：アルテナ レベル：4 ステータス：  • 魔術師：？ • 謎：？ 魔法：ディア・パナケイア • ディア・オルフェウス  フェルスは、ウラノスに所属する謎めいた魔術師である。フェルスはウラノスの直属として働き、彼からの命令なら何でも受け入れるが、必要に応じて独自に行動することもある。彼らは、不死をもたらした石を作り出した経験を、自身のトラウマと見なしている。' WHERE character_id = 'CH014270';
UPDATE characters SET description = '種族：人魚' WHERE character_id = 'CH014272';
UPDATE characters SET description = 'アリス・ロヴェルは冒険家であり、「アストラエア・ファミリア」の船長だった。' WHERE character_id = 'CH014273';
UPDATE characters SET description = '種族：ハーフドワーフ　身長：170 cm (5''7")　所属：ヘファイストス・ファミリア　レベル：5　到達階：59　ステータス：• 鍛冶師：？　ツバキ・コルブランドは、ヘファイストス・ファミリアの隊長であり、名匠でもある。 ツバキは大変親しみやすい性格で、様々な人々と気さくに交流し、フィンには「ハグしてもいい？」と尋ねたことさえある。ツバキはウェルフ・クロッツォに興味を持ち、彼の世話をしているが、彼が魔法の剣を作ることを拒んでいることを「才能の無駄遣いだ」と嘆いている。' WHERE character_id = 'CH014274';
UPDATE characters SET description = '種族：ゼノス　所属：ゼノス・ウラノス　レベル：5（推定）　グロスはガーゴイル型のゼノスである。ゼノスであるため、グロスは通常のモンスターよりもはるかに知性が高く、強力だ。彼は最強クラスのゼノスの一人であり、一級冒険者に匹敵する実力を持つ。 グロスは赤い目と一対の翼を持っている。その体は灰色の石でできている。  グロスは実直で頑固な性格だ。ゼノスの三人の指導者の一人として、同族を深く思いやり、彼らを守るためならどんな手段も厭わない。彼は' WHERE character_id = 'CH014275';
UPDATE characters SET description = '種族：ハーフエルフ　所属：ギルド　エイナ・トゥールは、ギルドの受付係であり、ベル・クラネルのアドバイザーである。エイナは5年前、学校を卒業した14歳の時にギルドに入会した。 当初はギルドで働くことにワクワクしていたが、すぐに自分が思っていたほど楽しい仕事ではないと気づき、やがて現在の性格へと変わっていった。4年後、ベルと出会い、彼のダンジョンアドバイザーとなった。　エイナは真面目で落ち着いた物腰を見せ、非常に賢く、姉のような' WHERE character_id = 'CH014276';
UPDATE characters SET description = '種族：人間　所属：タケミカヅチ・ファミリア　レベル：2　日立千草は、タケミカヅチ・ファミリアの一員である。内気で恥ずかしがり屋な性格だが、ファミリア、とりわけ想いを寄せるオウカに対しては忠実である。' WHERE character_id = 'CH014277';
UPDATE characters SET description = '「剣の姫」の異名を持つアイス・ヴァレンシュタインは、一級冒険者であり、ロキ・ファミリアの中心メンバーの一人である。ごく少数の一級冒険者の中でも、彼女は最強の一人として数えられている。' WHERE character_id = 'CH014278';
UPDATE characters SET description = '種族：ゼノス　所属：ゼノス「ウラノス」　レベル：4（推定）　レットはゴブリン系のゼノスである。ゼノスであるため、レットは通常のモンスターよりもはるかに知性が高く、強力である。  レットはベルを「ミスター」と呼んでいる。ベルは、彼が紳士のように振る舞おうとしていると述べている。ランイェの一行がイケロス・ファミリアに殺害されたことを知った後、他の冒険者たちを攻撃しようとしなかった数少ないゼノスの一人であったことから、彼には合理的な思考があることが示されている。' WHERE character_id = 'CH014279';
UPDATE characters SET description = 'ディアン・ケクト・ファミリアの一員。' WHERE character_id = 'CH014280';
UPDATE characters SET description = '彼は久我春義の生まれ変わりである。とても心優しく、大切な人々を守るためならどんなことでもする。' WHERE character_id = 'CH014281';
UPDATE characters SET description = 'セイカの生まれ故郷であるランブログ伯爵家で、奴隷として仕えていた少女。周囲には隠しているが、セイカでさえ見ることのできない「精霊」を見る力と、その精霊たちを追う才能を持っている。 幼い頃から、彼女を優しく扱ってくれたセイカに親しみを抱いてきた。' WHERE character_id = 'CH014282';
UPDATE characters SET description = 'セイカと同じように、ロドネール魔法学院の入学試験を受けに来た平民の少女。あらゆる属性の魔法に素質があり、剣術と魔法の両方に驚異的な才能を発揮して、入学試験で首席を獲得した。その実力から、彼女は魔王を倒せる「英雄」であるという噂が広まっている。' WHERE character_id = 'CH014283';
UPDATE characters SET description = '暗く冷たい雰囲気を漂わせる少女。彼女はセイカが通う学校の3年生だが、学年でトップの成績を誇るアミュではない。しかし、学校の校長の依頼により、セイカと共に帝都で開催される総合武道大会に出場することになった。' WHERE character_id = 'CH014299';
UPDATE characters SET description = 'アヤカシ。セイカが転生する前から使い続けているカンギツネである。独占欲が強く、超自然的な力を持つ、役に立たないマスコットキャラクターだが、心の底からセイカを愛している。 かつては成人女性のような姿をしていたが、この世界では何らかの理由で全体的に小さくなってしまった。普段は金狐の姿で、セイカの髪の中に隠れている。' WHERE character_id = 'CH014305';
UPDATE characters SET description = '久保なぎさは、『久保さんは僕（モブ）を許さない』のヒロインである。彼女は、白石を簡単に見つけられる数少ない人物の一人だ。' WHERE character_id = 'CH014328';
UPDATE characters SET description = '彼にはほとんど存在感がなく、そのため人々はしばしば彼を見過ごしてしまう。ただ、久保渚だけは例外で、彼女は彼を簡単に見つけ出すことができる。' WHERE character_id = 'CH014329';
UPDATE characters SET description = '雲仙先生は、穏やかで落ち着きのある人物として知られており、常に生徒たちがより良く、充実した人間へと成長できるよう導こうと努めています。' WHERE character_id = 'CH014330';
UPDATE characters SET description = '彼女は久保なぎさのいとこで、なぎさを尊敬しており、彼女のようになりたいと思っている。' WHERE character_id = 'CH014331';
UPDATE characters SET description = '久保と白石の同級生で、白石と同じ委員会に所属していたが、1年間も彼を見つけることができなかった。' WHERE character_id = 'CH014332';
UPDATE characters SET description = '彼女は久保なぎさの姉です。' WHERE character_id = 'CH014333';
UPDATE characters SET description = '久保とタマの友人。' WHERE character_id = 'CH014334';
UPDATE characters SET description = '彼女は久保と葉月の友人だ。' WHERE character_id = 'CH014335';
UPDATE characters SET description = '彼女は白石純太の母親です。' WHERE character_id = 'CH014336';
UPDATE characters SET description = '彼は白石純太の弟です。' WHERE character_id = 'CH014337';
UPDATE characters SET description = 'アニスフィアは、パレッティア王国の第一王女である。   前世の記憶を持つ彼女は、魔法の力で空を飛び回れるようになることを切望している。しかし、自身では魔法を使うことができないため、夢を叶えるべく、少々風変わりな研究に日々を費やしている。その奇抜な振る舞いから、「変わり者の王女」というあだ名がついた。' WHERE character_id = 'CH014338';
UPDATE characters SET description = 'マジェンタ公爵の娘。魔法に秀でているだけでなく、学問、政治、戦闘にも精通した天才的な美女である。アルガード王子の婚約者として、王国の次期女王としての将来を嘱望されていた。しかし、ある運命的な夜が、彼女の人生の軌道を永遠に変えてしまうことになる……' WHERE character_id = 'CH014339';
UPDATE characters SET description = 'アニスフィアの専属メイド。使用人ではあるが、姉のようにアニスフィアを見守っている。かつてアニスフィアに命を救われたことがあり、彼女に対して深い忠誠心を抱いている。' WHERE character_id = 'CH014340';
UPDATE characters SET description = '平民の娘でありながら、男爵の位に昇格した。身分の低い出自にもかかわらず、貴族学院において、有力な貴族の息子たちの注目を集めることに成功した。' WHERE character_id = 'CH014341';
UPDATE characters SET description = '強大な権力を誇るクラレット侯爵の長女。現在は私邸に身を隠し、呪術の研究に励んでいる。時折、アニスフィアと共同研究を行うこともあるが、二人の信念の違いから、その関係は複雑なものとなっている。' WHERE character_id = 'CH014342';
UPDATE characters SET description = 'ドラガス・サイアンは、かつて冒険者だったが後に貴族となり、レイニー・サイアンの父親である。' WHERE character_id = 'CH014343';
UPDATE characters SET description = 'パレッティア王国の女王。' WHERE character_id = 'CH014344';
UPDATE characters SET description = 'シャルトリューズ伯爵は魔法大臣であり、貴族の権威を脅かす可能性のあるあらゆる変革に反対するモーリッツ・シャルトリューズの父である。' WHERE character_id = 'CH014345';
UPDATE characters SET description = 'ユーフィリアの父。マジェンタ公爵家の当主であり、パレッティア王国の宰相、そしてオーファンズ王の親友でもある。' WHERE character_id = 'CH014346';
UPDATE characters SET description = 'パレッティア王国の皇太子。ユーフィリア・マジェンタと婚約している。' WHERE character_id = 'CH014348';
UPDATE characters SET description = 'パレッティア王国の王。' WHERE character_id = 'CH014350';
UPDATE characters SET description = '霊媒師。' WHERE character_id = 'CH014351';
UPDATE characters SET description = 'メープルは、『NewWorld Online』を始めたばかりのメインヒロインです。シールドクラスです。怪我をしたくないため、スキルポイントは常に「活力」に振り分けています。 そのため、多くのプレイヤーからは攻撃面では役に立たないと見なされていますが、意外にも彼女は自分なりのやり方でうまくやってのけています。少しおっちょこちょいなところもありますが、意外にも頭は良く、開発者が予想もしないような方法でゲームの仕組みを巧みに利用することがよくあります。ゲーム内での彼女の行動のほとんどは、ただ楽しむためだけのものであり、彼女は……' WHERE character_id = 'CH014353';
UPDATE characters SET description = 'カエデをVRMMORPG『ニューワールド・オンライン』に誘った、ゲーマーの女友達。彼女はプロゲーマーであり、その実力を証明する数々の実績を持っている。スワッシュバックラーというクラスをプレイしており、その反射神経は常人を超えていると言われている。  サリーは外向的で慎重、かつ現実的であり、それは他のゲームでの過去の経験が反映されている。また、彼女には創造的で狡猾な一面もあり、メイプルとのパーティーで「絶対にダメージを受けない」ようにするためにスワッシュバックラーを選んだことからも、それがうかがえる。' WHERE character_id = 'CH014354';
UPDATE characters SET description = 'その華奢な体格のせいで、よく女の子と間違えられる少年。メープルに誘われて「メープルツリー」に入会した。カナデは物静かで聡明で、あらゆる種類のパズルや謎に深い興味を示している。興味を持ったことには、たいてい丸一日を費やすほど没頭する。' WHERE character_id = 'CH014355';
UPDATE characters SET description = '双子の妹メイとともに、彼女たちはまだ第1層にいる間にメープルツリーにスカウトされる。' WHERE character_id = 'CH014356';
UPDATE characters SET description = 'ゲームの2つ目のイベントで、サリーとメープルと出会う。第一印象は良くなかったものの、やがて仲良くなり、最終的にメープル・ツリーに加入する。' WHERE character_id = 'CH014357';
UPDATE characters SET description = 'イズにメイプルを紹介した。ギルド制度が導入された後、彼は「メイプルツリー」への加入を招待された。彼は思いやりがあり、誠実で、柔軟な考えを持ち、真面目な人物だ。戦闘以外では、まるで親のような温かみを感じさせる。メイプルと同様、彼はシールドクラスに所属しているほか、剣術の習得にもなお励んでいる。' WHERE character_id = 'CH014358';
UPDATE characters SET description = '双子の妹・ユイと共に、まだ第1層にいる間にメイプルツリーにスカウトされる。' WHERE character_id = 'CH014359';
UPDATE characters SET description = '彼女は生産特化型のクラフタークラスをプレイしており、NWOでもトップクラスのクラフターの一人だ。メイプルからの招待を受けて、メイプル・ツリーに加入した。' WHERE character_id = 'CH014360';
UPDATE characters SET description = 'ドレッド（Dred または Dread）は、フレデリカやドラグと共に、ペインのギルド「聖剣の会」に所属している。鋭い直感の持ち主だ。その戦闘スタイルは高速攻撃と中程度の攻撃力を重視しているが、直感的には、ペインやメイプルには敵わないと感じている。' WHERE character_id = 'CH014361';
UPDATE characters SET description = 'ドラッグは、フレデリカやドレッドと共に、ペインのギルド「聖剣の会」に所属している。  彼は物腰は穏やかだが、振る舞いは荒々しい。その戦闘スタイルはイノシシのようで、猛烈な勢いで突進し、周囲を蹂躙する。この戦い方のため、彼に近い者でさえ、彼を支えるのに苦労している。' WHERE character_id = 'CH014362';
UPDATE characters SET description = '『NewWorld Online』の管理者の一人。' WHERE character_id = 'CH014363';
UPDATE characters SET description = 'フレデリカは、ドレッドやドラグと共に、ペインのギルド「聖剣の会」に所属しており、かなり強力なプレイヤーの一人である。' WHERE character_id = 'CH014364';
UPDATE characters SET description = '『ニュー・ワールド・オンライン』に登場するメープルのペットのカメ。' WHERE character_id = 'CH014365';
UPDATE characters SET description = '『NewWorld Online』の管理者の一人。' WHERE character_id = 'CH014366';
UPDATE characters SET description = 'ペインは『NewWorld Online』のトッププレイヤーであり、最強と目されている。彼はフレデリカ、ドレッド、ドラグと共に、ギルド「聖剣の集会」のギルドマスターを務めている。礼儀正しい人物ではあるが、メイプルを将来打ち負かすべきライバルと見なしている。' WHERE character_id = 'CH014367';
UPDATE characters SET description = 'ゲームに登場するサリーのペットのキツネ。' WHERE character_id = 'CH014368';
UPDATE characters SET description = 'シンは、ミー、マルクス、ミゼリーと共にギルド「フレイム・エンペラーズ」のメンバーである。彼は「デストラクター」の称号を獲得した。' WHERE character_id = 'CH014369';
UPDATE characters SET description = 'ゲームに登場するカスミのペットのヘビ。' WHERE character_id = 'CH014370';
UPDATE characters SET description = 'マルクス、あるいはマルクスは、ミー、ミゼリー、シンと共にギルド「フレイム・エンペラーズ」のメンバーである。マルクスは罠のスペシャリストであり、様々な罠や呪文を巧みに駆使して戦いを有利に進めるが、自分自身を疑う傾向がある。' WHERE character_id = 'CH014371';
UPDATE characters SET description = 'ゲームに登場するメイのペットのクマ。' WHERE character_id = 'CH014372';
UPDATE characters SET description = 'Miiは『NewWorld Online』のプレイヤーです。彼女は、Markus、Misery、Shinと共に、「Flame Emperors」ギルドのギルドマスターを務めています。Miiはあるスキルを獲得し、その卓越したカリスマ性によって、知らず知らずのうちに、周囲が自発的についてくるようなキャラクターを築き上げました。 このことに気づいた彼女は、かわいいものを楽しみたいだけの、物静かな本来の自分をさらけ出すのが恥ずかしくなってしまった。自分の行動を後悔しつつも、自分についてきてくれた人たちのために、表向きは堂々とした態度を貫くことにした。' WHERE character_id = 'CH014373';
UPDATE characters SET description = 'ゲームに登場するユイのペットのクマ。' WHERE character_id = 'CH014374';
UPDATE characters SET description = 'ミゼリーは、ミー、マルクス、シンと共にギルド「フレイム・エンペラーズ」のメンバーである。彼女はギルドのメインヒーラーを務めている。' WHERE character_id = 'CH014375';
UPDATE characters SET description = '『NewWorld Online』の管理者の一人。' WHERE character_id = 'CH014376';
UPDATE characters SET description = 'ドラゾウは、『NewWorld Online』のマスコット兼アナウンサーキャラクターです。' WHERE character_id = 'CH014377';
UPDATE characters SET description = '『NewWorld Online』の管理者の一人。' WHERE character_id = 'CH014378';
UPDATE characters SET description = 'ベルナルデッリ通信社の中堅記者。メリルの教育担当として彼女と共に旅をしている。酒好きで人付き合いが苦手な酒飲みだが、数々の戦いを乗り越えてきたベテランである。' WHERE character_id = 'CH014379';
UPDATE characters SET description = '「モネフ・ザ・ゲイル」は、ヴァッシュと戦った最初の「ガンホー・ガン」である。ナイフスは、ヴァッシュを殺すために必要な技量と力を身につけるべく、彼を独房に閉じ込め、20年間にわたって肉体鍛錬をさせた。 彼は動力式バトルスーツを身にまとい、両腕には2挺の高出力チェーンガンを装備している。背中に設置された加圧チャンバーにより、これらの銃は極めて高速で発射され、建物全体を吹き飛ばすほどの圧倒的な制止力を誇る。また、大きな布製のリュックサックには、eを含む多種多様な武器を携行している。' WHERE character_id = 'CH014385';
UPDATE characters SET description = 'E.G. マインは、球体を思わせるスーツを身にまとい、そのスーツには致命的なスパイクを展開するための制御用糸が内蔵されている暴力的な男である。マインはこれらの糸をさらに操り、敵に向かって投げつけることができる。    ウィキペディアより' WHERE character_id = 'CH014388';
UPDATE characters SET description = '「ダブルファング」のリーヴィオは、ウルフウッドの幼なじみであり、『アイ・オブ・マイケル』に登場する「ガンホー・ガンズ」の最後のメンバーである。彼は「ダブルファング」と呼ばれる、両腕に装着された十字形の小型機関銃を操り、その両端から発砲する。' WHERE character_id = 'CH014389';
UPDATE characters SET description = '彼女は3年生の学生です。' WHERE character_id = 'CH014398';
UPDATE characters SET description = 'アリアンは、ディオム魔法芸術アカデミーの1年生です。彼女はアメリアの幼なじみです。' WHERE character_id = 'CH014404';
UPDATE characters SET description = '種族：異世界の人' WHERE character_id = 'CH014411';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014412';
UPDATE characters SET description = '種族：ムーンライト・フェアリー' WHERE character_id = 'CH014413';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014414';
UPDATE characters SET description = '種族：ウッドエルフ' WHERE character_id = 'CH014415';
UPDATE characters SET description = '木杉の部下の一人。' WHERE character_id = 'CH014417';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014418';
UPDATE characters SET description = '種族：ブラック・クリスタル・フェアリー' WHERE character_id = 'CH014422';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014423';
UPDATE characters SET description = '種族：ドワーフ' WHERE character_id = 'CH014429';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014430';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014431';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014433';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014434';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014437';
UPDATE characters SET description = '種族：人間' WHERE character_id = 'CH014438';
UPDATE characters SET description = '木杉の部下の一人。' WHERE character_id = 'CH014439';
UPDATE characters SET description = 'マヒロの妹。飛び級を重ね、現在は大学に通う天才科学者。マヒロに薬を盛って、彼を少女に変えてしまった張本人である。' WHERE character_id = 'CH014440';
UPDATE characters SET description = '彼は引きこもりのニートで、孤独な生活を送っていたが、ある朝、妹に薬を盛られたせいで、目を覚ますと小さな女の子になっていた。' WHERE character_id = 'CH014441';
UPDATE characters SET description = 'モミジはカエデの妹です。彼女は中学生で、マヒロが復学した際に同じクラスに入りました。モミジはボーイッシュな服装や見た目、振る舞いを好んでおり、よく10代前半の少年と間違えられます。 しかし、モミジがトランスジェンダーのティーンであるような兆候は一切見られない。彼女は単にジェンダー・ノンコンフォーミングであるように見える。とはいえ、中学校の女子制服を着ている時や、かわいいジュ' WHERE character_id = 'CH014444';
UPDATE characters SET description = 'カエデはミハリの親しい友人だ。二人は中学校の頃から友人関係にある。ミハリはカエデよりも学業面で一歩先を行っているが、それでも二人は親しく、定期的に会っている。' WHERE character_id = 'CH014447';
UPDATE characters SET description = 'ネムはよく寝ている姿が見られる。彼女は一日中寝ており、体育の授業中や立ったままでも寝ていることがある。' WHERE character_id = 'CH014449';
UPDATE characters SET description = 'アサヒは、マヒロの中学校の同級生だ。彼女はマヒロと親しくなり、二人はかなり仲良くなる。アサヒは強い大阪訛りで話す。英語圏では、こうしたキャラクターには通常、南部訛りが強く与えられ、まるで「サザン・ベル」や「ディキシー・チック」を彷彿とさせる、南部の田舎娘のようなのんびりとした話し方になる。 彼女はマヒロの名前を「マーハイロー」と発音する。彼女は人を抱きしめるのが大好きで、特に友達を抱きしめるのが好きだ。マヒロは、アサヒからはいつも新鮮で清々しい香りがすると自分に言い聞かせている。' WHERE character_id = 'CH014450';
UPDATE characters SET description = '彼は四葉大学附属中学校の生徒で、大山真弘の同級生である。' WHERE character_id = 'CH014454';
UPDATE characters SET description = 'ミヨちゃんは、マヒロの中学校の同級生です。マヒロやアサヒと仲が良いです。ミヨちゃんは少し物静かで恥ずかしがり屋で、言葉で自分の気持ちを表現しないことがよくあります。 しかし、女子の同級生たちを抱きしめたり、ぎゅっと抱きついたりするのが好きで、彼女たちやその活動に大きな関心を寄せている。特に、 mahiro には、 mahiro より2、3歳年下であるにもかかわらず、強い関心を寄せるようになった。miyo-chan は、社交的な関心を女子のみに向けているようで、時間や関心を' WHERE character_id = 'CH014455';
UPDATE characters SET description = '彼は四葉大学附属中学校の生徒で、大山真弘の同級生である。' WHERE character_id = 'CH014458';
UPDATE characters SET description = '彼は四葉大学附属中学校の生徒で、大山真弘の同級生である。' WHERE character_id = 'CH014459';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：才能あるエンジニアであり、組織内の技術専門家として活躍しているが、彼女の発明品は、特に以前の学校に通っていた頃、度々大混乱を引き起こしていたことで知られている。  アネットは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。彼女は訓練学校に入学する前の記憶を一切持っておらず、自分が何者なのかさえ知らずに、その特別な能力ゆえにスパイとなった。' WHERE character_id = 'CH014461';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：交渉の達人であり、プロの誘惑者でもあり、その魅力を駆使して情報を引き出し、目的を達成することができる。　テアは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。 彼女はランプライトのメンバーの中で最年長かつ最も魅力的な存在であり、新聞社の社長の娘だったが、11歳の時に人質として拉致された。しかし、彼女が憧れていたスパイに救出され、その人物をきっかけに自らもスパイになることを決意した。' WHERE character_id = 'CH014463';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：動物の飼育や調教に才能があり、その技能を活かしてペットを訓練し、様々な任務で自分を補佐させている。  サラは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。臆病だが心優しい少女で、言葉の最後に「っす」と付け加える癖がある。田舎町のレストランのオーナー兼シェフの娘である。' WHERE character_id = 'CH014464';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：盗みが得意で、チームの中で最も運動神経に優れている。  シビラは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。彼女はギャングの家庭に生まれ、弟妹たちと共にギャングの活動を手伝わざるを得なかった。強い正義感を持ち、弟妹たちを守るためにスパイになることを志した。' WHERE character_id = 'CH014465';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト、インフェルノ　クラウスは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。ランプライトのボスであり、かつてはインフェルノのメンバーだったが、インフェルノが壊滅した後、ランプライトを再建した人物である。 自らを「世界一のスパイ」と称している。「世界一のスパイ」であるにもかかわらず、直感的に物事を進めるため、教えるのが非常に苦手である。' WHERE character_id = 'CH014466';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：標的を麻痺させたり殺したりできる毒を調合する才能がある。　リリーは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。彼女はランプライトのチームリーダーを務めている。 第一次世界大戦中の毒ガス攻撃を生き延びた際、スパイに命を救われたことがきっかけで、彼女自身もスパイになることを志した。ランプライトチームへの献身的な姿勢と自身の能力が評価され、クラウスによってランプライトのチームリーダーに任命された。' WHERE character_id = 'CH014467';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：天才的な才能を持ち、あらゆる技能に秀でているため、ランプライトのメンバーの中でも最も才能のあるスパイである。　モニカは『スパイ・クラスルーム』シリーズの主要な主人公の一人である。 芸術家の娘である彼女は、スパイになるために家出をし、短期間で訓練学校のトップ生徒となった。しかし、何らかの理由で急速に意欲を失い、成績不振の末にランプライトにスカウトされることになる。' WHERE character_id = 'CH014468';
UPDATE characters SET description = '職業：スパイ　所属：ランプライト　特技：変装に長けており、男性に扮しても見破られることはない。  グレテは『スパイ教室』シリーズの主要な主人公の一人である。彼女は政治家の娘だったが、何らかの理由で故郷を追われ、スパイになることを決意したようだ。頭脳は抜群だが、男性に対して根深い嫌悪感を抱いている。' WHERE character_id = 'CH014469';
UPDATE characters SET description = 'オリビアは、左派政治家ウヴェ・アッペルの主任メイドである。' WHERE character_id = 'CH014470';
UPDATE characters SET description = '暗殺者。' WHERE character_id = 'CH014472';
UPDATE characters SET description = '彼女は魔王軍の四天王の一人である。怒ったマリカを、彼女は極度に恐れている。' WHERE character_id = 'CH014491';
UPDATE characters SET description = 'ルークはイングリスの父親であり、セレーナの夫でもある。' WHERE character_id = 'CH014517';
UPDATE characters SET description = 'ラヘルは、ハイランドで生まれたわけではないけれど、ハイランダーだ。' WHERE character_id = 'CH014521';
UPDATE characters SET description = 'イリーナはセレナの姉であり、マーキスの妻である。' WHERE character_id = 'CH014523';
UPDATE characters SET description = 'セレナはイングリスの母親であり、ラファエルとラフィーニャ・ビルフォードの両方の叔母であると同時に、イリーナの妹でもある。' WHERE character_id = 'CH014525';
UPDATE characters SET description = 'ラファエルは、ビルフォード侯爵家の長男である。' WHERE character_id = 'CH014526';
UPDATE characters SET description = 'アリスティアこそが、イングリスに生まれ変わる機会を与えてくれる存在なのだ。' WHERE character_id = 'CH014527';
UPDATE characters SET description = 'クロは『極空水里（In/Spectre）』の男性主人公であり、岩永琴子の現在の恋人である。彼は不死と予知能力という超自然的な力を持っている。  クロは物静かで、争いを極力避ける傾向があり、自身の怪我にもほとんど気にかけない。治癒能力があるため、自身の安全をあまり気にしていない。（出典：『極空水里』ウィキ）' WHERE character_id = 'CH014528';
UPDATE characters SET description = 'コトコは『極空水里』のメインヒロインであり、現在、桜川クロの恋人である。彼女は非常に社交的な性格で、特に妖怪の助けを借りられる時は、どんな問題でもその根本原因を突き止めようと常に努力している。 危険を全く察知せず、クロに対してはべったりと甘える傾向がある。コトコは自己中心的で、悪戯好きを改める気など微塵もなく、他人のことをからかうのが好きで、少しエッチな面もある。また、かなり子供っぽい振る舞いを見せることも' WHERE character_id = 'CH014529';
UPDATE characters SET description = '彼女は、音無豪一の長男である音無涼馬の娘である。涼馬は店での用事があったため、リオンが彼の代わりに豪一の依頼に応じることにした。' WHERE character_id = 'CH014532';
UPDATE characters SET description = '愛する人々から数々の裏切りを受けたため、彼は人間への信頼を失い、人里離れた生活を送りたいと願うようになった。しかし実際には、彼は非常に高潔な人物であり、自分を裏切った者たちを許し、復讐など一切望んでいない。そのため、彼のあまりにも寛大な振る舞いに、多くの人々が戸惑いを隠せない。' WHERE character_id = 'CH014533';
UPDATE characters SET description = '小さな港町で、幽霊の猫と一緒に暮らす老婆。80歳を過ぎているが、健康で、町の人々から頼りにされている。' WHERE character_id = 'CH014535';
UPDATE characters SET description = '戸平善太が亡くなる前に、亡くなった孫をモデルにして作った木製の人形。' WHERE character_id = 'CH014536';
UPDATE characters SET description = '彼女は「スノーイ」という名前にふさわしく、滑らかで白い肌を持つ、とても美しい女性です。髪は黒と白が混ざった長い髪をしています。よく白い着物を着ています。彼女は、人間にしては優しすぎると思っている室井雅之のことを、心から気にかけています。' WHERE character_id = 'CH014538';
UPDATE characters SET description = 'テと一緒に暮らしている、おしゃべりな猫。お酒を飲むのが大好きだ。' WHERE character_id = 'CH014540';
UPDATE characters SET description = 'リッカは桜川クロウの年上の従姉であり、彼があれほど頻繁に病院に通っていた理由でもある。クロウと同じように、彼女も不死と予知の能力を持っているが、その能力を取り除きたいと願い、医学的治療や自殺を試みたものの、いずれも失敗に終わっている。' WHERE character_id = 'CH014541';
UPDATE characters SET description = '正之の元同僚。' WHERE character_id = 'CH014546';
UPDATE characters SET description = 'リッカが引っ越してきたアパートの管理人。' WHERE character_id = 'CH014547';
UPDATE characters SET description = 'カズユキの彼女。' WHERE character_id = 'CH014552';
UPDATE characters SET description = 'アンが購入した、非常に腕の立つ戦士フェアリー。オブシディアンから生まれたため、いつもとても肌の色が濃い。また、口が鋭い。' WHERE character_id = 'CH014557';
UPDATE characters SET description = 'キャンディ職人。背が高く、ほっそりとしていて、髪は小麦のような色をしている。彼女の夢は、母親のように「シルバー・シュガー・マスター」になることだ。彼女は、シャルやミスリルと対等な関係を築けるよう、精一杯努力している。' WHERE character_id = 'CH014558';
UPDATE characters SET description = 'かつてアンに妖精ハンターから助けられた、小さな労働の妖精。恩返しをするために、今はアンと一緒にいる。話していないときはとてもかわいい。水滴から生まれた。' WHERE character_id = 'CH014562';
UPDATE characters SET description = '裕福な菓子職人の息子。アンはしばらくの間、彼にタダ乗りしていた。彼はアンのことが好きだ。' WHERE character_id = 'CH014566';
UPDATE characters SET description = 'ハイランドの王' WHERE character_id = 'CH014571';
UPDATE characters SET description = 'アンの母親' WHERE character_id = 'CH014572';
UPDATE characters SET description = 'ハイランドの女王' WHERE character_id = 'CH014573';
UPDATE characters SET description = 'クリス・レッドグレイブの父。' WHERE character_id = 'CH014575';
UPDATE characters SET description = 'IT企業MizerkaのCEO' WHERE character_id = 'CH014582';
UPDATE characters SET description = '佐藤ウェンディの父親。' WHERE character_id = 'CH014589';
UPDATE characters SET description = '日本では平凡な会社員として平穏な日々を送っていたが、眠りの中でこの世を去った主人公。 その勤勉で親切な振る舞いにより、神々の御加護を受け、8歳の少年として異世界へと送り出された。そこで彼は3年間、森の中で暮らし、スキルを磨き、数百匹のスライムを調教し、戦闘や狩猟から掃除やクラフトに至るまで、様々な作業でスライムの多彩な能力を活用していた。 やがて、彼を温かく迎え入れてくれるジャミル一家と出会う。' WHERE character_id = 'CH014595';
UPDATE characters SET description = 'ジャミル公爵家の後継者であるエリアリアは、11歳の少女で、リョーマの親友となる。リョーマと同様、彼女もモンスターテイマーであり、その体には大きな魔法の素質が備わっているが、リョーマから正しい鍛錬の方法を教わるまでは、その力を制御するのに苦労していた。（出典：ウィキペディア）' WHERE character_id = 'CH014596';
UPDATE characters SET description = '冒険者ギルド・ギムル支部の支部長。（出典：ウィキペディア）' WHERE character_id = 'CH014598';
UPDATE characters SET description = '猫型のビーストマンで、Bランクの冒険者。竜馬が冒険者になって初めて受けた依頼が彼女の家の掃除だったことから、彼の最初の依頼主となり、後に友人となる。（出典：ウィキペディア）' WHERE character_id = 'CH014605';
UPDATE characters SET description = '魔法と学問の神。' WHERE character_id = 'CH014607';
UPDATE characters SET description = '「バンブー・フォレスト」の社員。カラムの双子の兄弟' WHERE character_id = 'CH014617';
UPDATE characters SET description = 'バンブー・フォレストの社員。カーラの双子の姉妹' WHERE character_id = 'CH014622';
UPDATE characters SET description = '元暗殺者。現在はバンブー・フォレストの社員。<a href="https://anilist.co/character/197880/Li-Ling">李凌</a>の父。' WHERE character_id = 'CH014623';
UPDATE characters SET description = '技術と職人技の神。' WHERE character_id = 'CH014627';
UPDATE characters SET description = '元暗殺者。現在はバンブー・フォレストの従業員。<a href="https://anilist.co/character/197881">フェイ・リン</a>の娘。' WHERE character_id = 'CH014628';
UPDATE characters SET description = '商人ギルドのギルドマスター' WHERE character_id = 'CH014632';
UPDATE characters SET description = 'サリアはレベル700の獣人ゴリラだが、「進化の果実」の力を借りて進化すると女性となり、それ以降は人間の姿やゴリラの姿に自由に行き来できるようになるほか、部分的な変身も可能となる。' WHERE character_id = 'CH014638';
UPDATE characters SET description = '神月カレンは、柊誠一とともに異世界へ転移した「英雄」の一人である。' WHERE character_id = 'CH014641';
UPDATE characters SET description = '彼女はAクラスの冒険者だが、不運の呪いにかかっているため、「災厄」という異名で呼ばれている。' WHERE character_id = 'CH014647';
UPDATE characters SET description = '彼女は進化する前はロバだった。' WHERE character_id = 'CH014650';
UPDATE characters SET description = 'ギルドマスター。' WHERE character_id = 'CH014656';
UPDATE characters SET description = 'ギルドの受付係。' WHERE character_id = 'CH014658';
UPDATE characters SET description = '魔軍第3戦隊の隊長。' WHERE character_id = 'CH014660';
UPDATE characters SET description = '山野三葉は、崖から転落したことをきっかけに異世界へと飛ばされ、そこで特別な能力を手に入れた日本の高校生だ。三葉は聡明な少女である。 彼女はその知性を駆使して、自分や他人の問題を解決する。その答えや解決策は年齢不相応なほど成熟しており、周囲を驚かせる。というのも、小柄な体格から、周囲は依然として彼女を幼いと思っているからだ。彼女は優れた女優であるだけでなく、非常に抜け目もなく、状況を巧みに切り抜けることで困難な局面を回避している。' WHERE character_id = 'CH014661';
UPDATE characters SET description = '侯爵の令嬢。ゲーム『i』『Love Me Magically! (Magikoi)』</i>では、自分の気持ちをうまく伝えられないことが原因で、破滅という運命をたどることになる。' WHERE character_id = 'CH014678';
UPDATE characters SET description = '『i』『Magikoi』</i>のヒロイン。' WHERE character_id = 'CH014679';
UPDATE characters SET description = 'リゼロッテの婚約者であり、『マジコイ』の主人公。フィッツェンハーゲン王国の皇太子であり、魔法学園の生徒会長でもある、まさに「王子」その人である。 彼は、試合中に突然聞こえてきた実況を、光の女神リレナからの導きだと受け止め、神の声として崇めている。' WHERE character_id = 'CH014680';
UPDATE characters SET description = 'シホノの姉。' WHERE character_id = 'CH014685';
UPDATE characters SET description = '風巻まつりの幼なじみである「あやかし乙女」。彼女は数少ない「あやかし」が見える人間の一人で、あやかしに対してとても親しみを持って接することが多い。しかし、その「乙女」という立場ゆえに、悪意を持つあやかしたちの標的となってしまっている。' WHERE character_id = 'CH014714';
UPDATE characters SET description = '強力な妖怪であり、妖怪の王である。彼は鈴奏を追い、彼女を喰らって自らの力を増そうとしている。' WHERE character_id = 'CH014715';
UPDATE characters SET description = '幼なじみの奏・鈴と共に、あやかし（精霊の一種）を見ることができる少年。祖父から、鈴が「あやかし乙女」であることを知らされた後、彼女を危険から守るために、除霊忍者となった。' WHERE character_id = 'CH014716';
UPDATE characters SET description = '彼は風巻一族の忍者・除霊師であり、風巻マツリの祖父である。' WHERE character_id = 'CH014717';
UPDATE characters SET description = '歌川ガラクは、筆から生まれた妖怪であり、人間の姿をとっており、有名な画家としての身分も持っている。' WHERE character_id = 'CH014718';
UPDATE characters SET description = 'ルーシーは、奏すずの同級生であり友人です。物静かで内気なタイプですが、何でもかんでもSNSに投稿したくなるような写真を撮るのが大好きです。普段はいつも鳥羽弥生と一緒にいます。' WHERE character_id = 'CH014719';
UPDATE characters SET description = '小荻レオは、小荻一族の忍者であり、風巻マツリの忍者用装備の製作者である。' WHERE character_id = 'CH014720';
UPDATE characters SET description = '弥生は、奏・鈴の同級生であり友人だ。彼女はいつもルーシーと一緒にいる。' WHERE character_id = 'CH014721';
UPDATE characters SET description = '曽我二ノクルは、二ノクル一族出身の忍者・除霊師であり、風巻マツリをライバルと見なしている。' WHERE character_id = 'CH014723';
UPDATE characters SET description = '成宮湊は、このシリーズの主人公である。風舞高校の1年生で、弓道部の部員だ。  湊は、小学6年生の時の事故や、中学最後の大会でのターゲットパニック事件をきっかけに、内気で引きこもりがちな性格になってしまった。真面目で責任感が強く、家事をきちんとこなし、学校の弓道場の掃除も率先して行っている。その真面目さゆえに、七尾や良平のような明るい性格の人たちに、しばしば戸惑わされてしまう。' WHERE character_id = 'CH014777';
UPDATE characters SET description = '竹早星矢は、風舞高校の1年生で、弓道部の部員であると同時に、部会長兼男子部キャプテンも務めている。星矢は、成熟していて頼りになり、親切な性格として知られ、港が弓道で成功できるよう支援し、見守ることに尽力している。 しかし、第2話で彼自身が語ったように、本気を出した時には、思いやりなど必要としない。セイヤとミナトは隣同士ということもあり、幼い頃から親友同士だ。リョウヘイを加えた3人は' WHERE character_id = 'CH014778';
UPDATE characters SET description = '山之内亮平は、風舞高校の1年生で、弓道部の部員である。亮平は湊や星矢とは幼なじみで、5年生で転校するまでは幼稚園や小学校を共に過ごし、中学校は彼らとは別の学校に進んだ。 中学校では、必修の武道科目の一環として弓道の授業を受けていた。  リョウヘイは、セイヤの知性と誰に対しても親切な人柄を大いに尊敬しており、そのことを頻繁に称賛している。H' WHERE character_id = 'CH014779';
UPDATE characters SET description = '如月七尾は、風舞高校の1年生で、弓道部の部員である。幼い頃から、その容姿とカリスマ性により、多くの女性ファンに慕われてきた。 しかし、その反面、嫉妬による攻撃も数多く受けるようになったため、母親や叔母たちは、いとこのカイトに彼のボディーガードを任せることにした。この策は小学校時代にはうまく機能し、中学校では別々の学校に進学したものの、課外活動や塾では相変わらず一緒に過ごしていた。ソム' WHERE character_id = 'CH014780';
UPDATE characters SET description = '小野木海斗は、風舞高校の1年生で、弓道部の部員である。海斗は短気で、真面目すぎて、攻撃的な印象を与える。 特に、いとこのナナオに「カッちゃん」と呼ばれたり、誰かが自分ほど真剣に物事に向き合っていないと感じたりすると、すぐに腹を立ててしまう。物言いは率直で、本音を隠すことはない。また、早合点しがちである。そのため、周囲の人々は彼を恐れている。彼の現在の性格の大部分は、' WHERE character_id = 'CH014781';
UPDATE characters SET description = '滝川雅樹は八咫神社の参拝司祭であり、後に風舞高校弓道部の指導者となる。弓道五段の有段者である。雅樹は神秘的で気品のある青年という印象を与えるが、実際には見た目よりも気さくで気取らない性格だ。 若くして老成した雰囲気を持っている。弓道以外の多くの場面では、大雑把でだらしがない振る舞いをすることで知られている。形式ばったことを嫌うようで、皆に「マサさん」と呼ぶよう頼んでいる。彼は' WHERE character_id = 'CH014782';
UPDATE characters SET description = '辻見根高校の2年生で、同校の弓道部の部員である。' WHERE character_id = 'CH014783';
UPDATE characters SET description = '白菊ノアは、風舞高校の1年生で、弓道部の部員である。' WHERE character_id = 'CH014784';
UPDATE characters SET description = '辻見根高校の2年生で、同校の弓道部の部員である。' WHERE character_id = 'CH014786';
UPDATE characters SET description = '菅原万治は、桐崎高校の1年生で、弓道部の部員である。菅原千一の双子の弟である。' WHERE character_id = 'CH014787';
UPDATE characters SET description = '辻峰高校の3年生で、弓道部の部員。' WHERE character_id = 'CH014788';
UPDATE characters SET description = '菅原千一は、桐崎高校の1年生で、弓道部の部員である。菅原万治の双子の兄である。' WHERE character_id = 'CH014789';
UPDATE characters SET description = '辻見根高校の2年生で、同校の弓道部の部員である。' WHERE character_id = 'CH014790';
UPDATE characters SET description = '藤原修の妹。' WHERE character_id = 'CH014791';
UPDATE characters SET description = '辻峰高校の3年生で、同校の弓道部の部長を務めている。' WHERE character_id = 'CH014792';
UPDATE characters SET description = '瀬尾リカは、風舞高校の1年生で、弓道部の部員であり、女子チームのキャプテンを務めている。' WHERE character_id = 'CH014793';
UPDATE characters SET description = '本村弘樹は、桐崎高校の3年生で、弓道部の部長を務めている。' WHERE character_id = 'CH014794';
UPDATE characters SET description = '花沢ユウナは、風舞高校の1年生で、弓道部の部員である。' WHERE character_id = 'CH014795';
UPDATE characters SET description = '西園寺和義は、成宮湊と藤原修にとって最初の弓道指導者である。ライトノベルでは男性だが、アニメでは女性となっている。' WHERE character_id = 'CH014796';
UPDATE characters SET description = 'ロンドンで最も有名な探偵' WHERE character_id = 'CH014822';
UPDATE characters SET description = '所属：帝国軍情報部、アイアンブラッズ　国籍：エレボニア　上級情報将校であり、帝国軍情報部の責任者である。 彼は「アイアンブラッズ」の一員であり、ギリアス・オズボーン首相が自ら選んだ側近の一人である。交渉を専門としており、通常はエレボニアと敵対する勢力との交渉のため、世界各地へ派遣される。諜報将校としての仕事に関しては非常に真面目で冷徹であり、状況を好転させる可能性のあるあらゆる手段を講じる傾向がある。' WHERE character_id = 'CH014839';
UPDATE characters SET description = '所属：トールス軍事アカデミー、政府監察局　国籍：エレボニア　同級生全員に対して厳しい基準を課す天才学生。第7学級の副学級長であり、学業成績ではエマ・ミルシュタインに次ぐ2位である。 彼の顕著な特徴は、貴族階級全体に対する嫌悪感である。彼は、首都ハイムダルルの帝国総督カール・レグニッツの息子である。' WHERE character_id = 'CH014840';
UPDATE characters SET description = '所属：ウロボロス　ウロボロスに所属する謎めいたトリックスター。ゼロス・エンフォーサーであり、主にウロボロスのアンギスたちが遂行する計画を見守る役割を担っている。 彼は「セレスティアル・グローブ」、すなわちグランドマスター本人に直接報告を行う。シリーズ全体を通じて、彼は全く老けていないように見える。彼は「アーツ」や「コンバット・オーブメント」の助けを借りずに魔法を使うことができる。' WHERE character_id = 'CH014842';
UPDATE characters SET description = '所属：鉄道憲兵隊、アイアンブラッズ　国籍：エレボニア　エレボニア帝国の大陸横断鉄道システムの警備を専任とする軍事組織「鉄道憲兵隊」の大尉。また、オズボーン首相が最も信頼を寄せる側近である「アイアンブラッズ」の一員でもある。 クレアは、事象を把握し、それを全体として計算できる、並外れた認知能力を持っていることで知られている。軍服を身にまとうと、彼女は極めて冷徹で計算高い人物となる。' WHERE character_id = 'CH014845';
UPDATE characters SET description = '国籍：エレボニア　所属：　エレボニア帝国出身のハンサムな金髪の男性で、旅する音楽家だと名乗っている。彼は確かにほぼすべての楽器において卓越した音楽的才能に恵まれているが、極めて無鉄砲で、風変わりな趣味の持ち主でもある。 彼の奇行としては、地元のレストランでの演奏後に途方もなく高価なワインを飲み干して（そのせいで投獄された）、他の魅力的なキャラクター全員に何度も言い寄る（彼自身は「愛の狩人」だと自負している）ことなどが挙げられる。' WHERE character_id = 'CH014846';
UPDATE characters SET description = '国籍：エレボニア　所属：エレボニア帝国政府、アイアンブラッズ　エレボニア帝国政府の宰相であり、皇帝から厚い信頼を得て帝国の内政を全面的に掌握し、首都ヘイムダルにあるヴェルミリオ宮を統括している。 平民として生まれた彼は、エレボニア帝国の貴族体制に強く反対している。貴族から権力を奪い、帝国政府に委ねようとする改革派の象徴的存在である。狡猾で、' WHERE character_id = 'CH014847';
UPDATE characters SET description = '国籍：エレボニア　所属：ラマレ州軍、トース軍事アカデミー分校（校長）　レ・ギン伯爵の娘、アウレリア・レ・ギン。 彼女は、帝国で名高い二つの剣術流派、ヴァンダー流とアルセイド流の両方を極めた、現存する唯一の達人である。戦場では「黄金のラークシャサ」として知られ、手ごわい戦士であり名将でもある。彼女は、それぞれの流派の達人を極め、最終的には彼らを凌駕することで、強さの頂点に立つことを目指していた。' WHERE character_id = 'CH014848';
UPDATE characters SET description = '所属：ブレイサーギルド　国籍：リベルリアン　『空の軌跡』の主人公。明るく陽気で、いつも前向きな少女。多くの人から、無鉄砲なほど短気だと言われている。計画や行動が及ぼす影響をあまり考えず、思いつきで即座に行動に移してしまう。 とはいえ、この短気さと無鉄砲さは、彼女の強い正義感に由来している。カシウス・ブライトの娘であり、ブラッサーでもある。愛用する武器はボ' WHERE character_id = 'CH014849';
UPDATE characters SET description = '所属：トールス軍事アカデミー第VII期生、トールス軍事アカデミー分校第VII期生指導教官、エレボニア帝国軍、シュヴァルツァー男爵領　国籍： エレボニア人。レアン・シュヴァルツァーは、トールス軍事アカデミーにおいて「第7期生」と称される実験クラスの一員に選ばれた生徒の一人であり、『トレイルズ オブ コールド スチール』シリーズの「エレボニア編」における主人公である。 レアンは、帝国の北部領地イミール出身の下級貴族の家系に生まれた。卒業後、' WHERE character_id = 'CH014850';
UPDATE characters SET description = 'ルファス・アルバレアは、四大名家のひとつを率いるヘルムート・アルバレア公の長男であり、ジュシス・アルバレアの異母兄弟として登場する。' WHERE character_id = 'CH014851';
UPDATE characters SET description = '国籍：エレボニア　所属：サザーランド州軍、サザーランド州軍准将。同軍は、エレボニア南部の防衛を担う軍隊である。 彼は、獅子の戦争においてドレイチェルス・ライゼ・アルノール皇帝を支援し、その後エレボニアに移住したノルド族の末裔であり、その功績により一族は帝国社会において貴族の地位を確立した。彼は、ノルド高地発祥の「バルディアス剣術流派」の継承者である。その技量は……' WHERE character_id = 'CH014852';
UPDATE characters SET description = '所属：ブレイサーギルド　黒髪に琥珀色の瞳を持つ物静かな青年で、短気なエステルが深刻なトラブルに巻き込まれないよう、常に傍らで支えている。 武器は双剣。ロレントの郊外で、カシウス・ブライトとエステル・ブライトと共に暮らしている。物語の冒頭で、エステルと共にブレイサー試験を受けた。かなりの美青年として知られているが、自分に向けられる恋愛的なアプローチには全く気づいていない。' WHERE character_id = 'CH014853';
UPDATE characters SET description = '所属：ノーブル・アライアンス、国籍：エレボニア 『トライルズ オブ コールドスチール II』の物語において、アルティナはノーブル・アライアンスに所属し、本作の敵役として登場する。彼女には「クライオム・ソライス」という名の漆黒のコンバットシェルが付き従っており、精神的な絆を通じて彼女のあらゆる命令に従う。 アルティナは人間の感情を理解できないため、時折、自分の感情を表現するのに苦労することがある。' WHERE character_id = 'CH014854';
UPDATE characters SET description = '劇的な演出を好む怪盗であり、常に自らの活躍を広く知らしめようと試みる。怪盗ブルーブランは、強烈なナルシシズムを特徴とする人物だと言えるだろう。怪盗として、彼は変装と潜入の達人である。 彼が盗めないものなど何もないが、彼は美的な価値が極めて高いものしか盗まない。美を追求するという共通の情熱ゆえに、彼とオリヴィエは互いに一種のライバル関係を築き、どちらの美が' WHERE character_id = 'CH014855';
UPDATE characters SET description = '所属：クロスベル警察署 特別支援課　国籍：クロスベル人　特別支援課に配属されている若手刑事。 クロスベル警察署に採用される前は、カルヴァード共和国に住んでいた。非常に若い年齢で刑事免許を取得した、才気あふれる刑事として知られている。生まれ持った指導力と、人々を鼓舞し率いるカリスマ性により、特別支援課の事実上のリーダーとしての役割を果たしている。' WHERE character_id = 'CH014856';
UPDATE characters SET description = '国籍：エレボニア　所属：帝国情報部、トース軍事アカデミー第7期生　帝国情報部に所属する小柄な少女。「エアゲットラム」と呼ばれる銀色のヒューマノイド型シェル・パペットと結びついている。 性格は非常に子供っぽく、おしゃべりなところがあり、そのせいで諜報員としてはあまり適していない。それでも、彼女の破壊力は同部門にとって大きな戦力となっている。彼女はジュシス・アルバレアにかなり執着しており、彼にとっては悩みの種となっている。' WHERE character_id = 'CH014858';
UPDATE characters SET description = '所属：シュタールリッター騎士団　アリアンロッドによって設立された騎士団「シュタールリッター」の団長。主君に対して揺るぎない忠誠心を捧げる、厳格な騎士である。 ほとんどのことにおいてアリアンロッドの右腕として振る舞い、比類なきスピードを誇る恐るべき戦士であり、「疾風デュヴァリー」という異名を持つ。 厳格な一面がある一方で、おっちょこちょいで不器用な一面も持ち合わせており、そのせいで仲間の騎士たちや敵から絶え間なくからかわれており、本人はそれを大変嫌がっている。' WHERE character_id = 'CH014859';
UPDATE characters SET description = '所属：アルク・アン・シエル劇団、国籍：カルヴァルド人　アルク・アン・シエル劇団の期待の新星。 同劇団の看板スター、イリヤ・プラティエールに直接スカウトされた。元々はカルヴァードからクロスベルを訪れていた旅人。非常にスレンダーで身軽なため、この道には天性の才能がある。イリヤと並んで主演を務め、国内外で多くの熱心なファンを獲得している。' WHERE character_id = 'CH014860';
UPDATE characters SET description = '所属：トールス軍事アカデミー第7期生、ヘイムダル音楽アカデミー　国籍：エレボニア　著名な軍人、クレイグ・ザ・レッドの息子。エリオットは、音楽に並外れた才能を持つ聡明な若者である。 当初はハイムダルにある音楽アカデミーで音楽を学びたかったが、父の反対により、やむなくトールスに入学することになった。そこで第7学級に配属され、リアンと出会い、その後の展開は周知の通りである。第7学級での日々を通じて成長を遂げたエリオットは、早期卒業を果たし、' WHERE character_id = 'CH014862';
UPDATE characters SET description = 'サトシ（海外では主に「アッシュ・ケッチャム」として知られる）は、アニメ『ポケットモンスター』の主人公である。また、アニメを原作とする『電脳ピカチュウ』、『サトシとピカチュウ』、『ポケットモンスター ダイヤモンド・パール』など、さまざまな漫画作品の主人公でもある。 彼はマサラ町出身のポケモントレーナーで、ポケモンマスターになることを目標としている。彼の最初のポケモンは、オキド教授の研究室に遅れて到着した際に、オキド教授からもらったピカチュウだった。彼は' WHERE character_id = 'CH014863';
UPDATE characters SET description = 'ピカチュウは『ポケットモンスター』アニメの象徴的なポケモンであり、サトシがポケモントレーナーとしての旅の途中で、オキド博士から譲り受けた最初のポケモンです。' WHERE character_id = 'CH014864';
UPDATE characters SET description = 'タケシはデビューエピソードで、主にサトシの対戦相手として登場した。後のジムリーダーたちとは異なり、彼は「世界一のポケモンブリーダー」になることを目指し、サトシの旅に同行することを申し出た。  タケシは他の主要キャラクターたちより数歳年上であるため、主に彼らへの助言役を務めている。ポケモンバトルの知識が豊富で、サトシと他のキャラクターたちの対戦ではしばしば審判を務める。また、タケシは自らを「女性にもてる男」だと自負しており、' WHERE character_id = 'CH014865';
UPDATE characters SET description = 'カスミは、正式名称を「ハナダジム」というハナダ市のジムのジムリーダーである。彼女は、バトルで自分を倒したトレーナーに「カスケードバッジ」を授与する。水タイプのポケモンを専門としている。  カスミは、アニメの主人公・サトシの友人であり、かつての旅の仲間でもある。サトシが彼女の自転車を盗み、うっかり壊してしまったことをきっかけに、カスミはサトシの後を追って関東地方、オレンジ諸島、そしてジョウト地方を巡り、彼と過ごした時間を活かしてジムリーダーになるという目標に向かって努力を重ねた。' WHERE character_id = 'CH014866';
UPDATE characters SET description = 'シゲルはサトシとほぼ同い年のキャラクターである（ただし、二人の身長の差から、シゲルの方が若干年上であると推測される）。ゲームによると、二人は幼い頃は遊び仲間であり隣同士の住人だったが、共にポケモンへの情熱を見出したことをきっかけに、次第に距離ができてしまった。 シリーズの序盤から、サトシとのライバル関係が繰り返し描かれるモチーフとなる。ゲーム、漫画、アニメと同様に、シゲルは自信過剰で傲慢なトレーナーとして描かれている。' WHERE character_id = 'CH014867';
UPDATE characters SET description = '彼女はアッシュの母親です。デリアは息子をとても大切にしており、いつも「精一杯頑張るように」と彼に言い聞かせています。彼女は非常に才能に恵まれており、ミスコンで優勝したほか、インディゴ高原のトップシェフたちからレシピを求められるほど人気のある料理を作り上げたこともあります。 サトシの父親が誰なのかは不明だが、サトシが家を出てから少なくとも一度は彼に連絡を取っていることから、両親が別居しているかどうかは定かではない。彼女には、家事を手伝ってくれるだけでなく、バトルにもかなり長けたミスター・マイムの家政婦がいる。' WHERE character_id = 'CH014868';
UPDATE characters SET description = 'バリちゃんという名のバリアードは、現在、サトシの母親であるハナコさんと一緒に暮らしている。' WHERE character_id = 'CH014869';
UPDATE characters SET description = 'リザードンは、竜のような姿をした二足歩行のポケモンです。体は主にオレンジ色で、胸から尾の先にかけてはクリーム色をしています。首は長く、青い小さな目と、わずかに隆起した鼻孔を持ち、長方形の頭の後ろからは2本の角のような突起が突き出しています。 口を閉じた状態でも、上顎には2本の牙が見える。背中からは、裏側が青緑色の2枚の大きな翼が生えており、それぞれの翼の第3関節からは角のような突起が突き出ている。翼には1本の翼指があり、' WHERE character_id = 'CH014870';
UPDATE characters SET description = 'ハハコモリは、細身で黄色い、二足歩行の昆虫型のポケモンです。大きくて丸い頭の周りには、幅広で裂けた葉があり、先端が半円形になった長い触角を持っています。目は赤く、白目が見えません。 小さな胸部は濃い緑色で、長い腹部は黄色く、緑色の葉で覆われている。手は長く葉のような形をしており、それぞれに「かじり跡」がある。上腕も葉のような形をしているが、上部に黄色い葉脈がある。細い脚は黄色で、その周囲には濃い緑色の太い節があり、' WHERE character_id = 'CH014871';
UPDATE characters SET description = 'ハブナケは、通常、アコーディオンのように丸まった姿で描かれるヘビ型のポケモンです。体色は主に黒ですが、体にはいくつかの模様があります。頭から尾にかけて黄色い六角形の模様があり、地面に触れる部分には小さな黄色い突起があり、さらに紫色の傷跡のような模様がいくつかあります。 上顎からは細長い赤い牙が突き出ており、鋭い赤い目をしている。尾は一部が赤く、刃のような形をしている。ハブナケは岩で尾を研ぎ、それを用いて' WHERE character_id = 'CH014872';
UPDATE characters SET description = 'ムスキッパは、ハエトリグサに似た緑色のポケモンです。丸い目には小さな瞳孔があり、とげとげしい歯を持っています。茎は黄色で緑色の斑点があり、その下には触手のような赤と緑のつるが生えています。 このつるを使って木の枝にぶら下がることができ、まるで植物のように見えると言われています。葉のような腕が2本あり、それぞれに3本の葉のような「指」があります。口は約180度まで大きく開くことができます。口を大きく開けて、甘い香りで待ち構える獲物を誘い寄せます。' WHERE character_id = 'CH014873';
UPDATE characters SET description = 'ナース・ジョイは、これまでに発売されたすべての『ポケットモンスター』シリーズに登場する定番キャラクターです。どの町や都市、地域にも複数のナース・ジョイがいます。彼女たちは皆、見た目が同じで、声や性格も同一です。なぜすべてのナース・ジョイが同じように見えるのかについては、さまざまな憶測が飛び交っていますが、どうやら彼女たちは何らかの形で親戚関係にあるようです。   しかし、性格や外見が異なるナース・ジョイが登場した例もいくつかあります（例えば、『オレンジ諸島』に登場する、攻撃的で日焼けしたナース・ジョイなど）。' WHERE character_id = 'CH014874';
UPDATE characters SET description = 'カビゴンは、クリーム色の顔、お腹、足を持つ、巨大な二足歩行の濃青緑色のポケモンです。手足は比較的小さいため、体の大部分はお腹で占められています。頭は大きく、小さくて尖った耳と、下顎から突き出た2本の尖った歯があります。 足は丸く、それぞれに3本の爪と円形の茶色の肉球があり、腕は短く、両手にはそれぞれ5本の爪がある。カビゴンはその巨体ゆえに、ノーマルタイプのポケモンの中で最も重い。カビゴンは山や森によく生息している。それは……' WHERE character_id = 'CH014875';
UPDATE characters SET description = 'キングラーは、カニに似た甲殻類のポケモンです。強靭な甲羅が体の外側を覆っており、上半身は赤く、下半身は淡い黄褐色をしています。上半身の上部には、王冠のような6本の高くて細い棘が生えています。 薄茶色の腕も上半身に繋がっている。下半身は顎の役割も兼ねており、6本の牙が上半身と重なり合っている。外側の2本の牙は内側の4本よりもはるかに大きく、キングラーの体長の約半分ほどの長さがある。腰の部分がはっきりと突き出ている。' WHERE character_id = 'CH014876';
UPDATE characters SET description = 'モロバレルは、キノコのような姿をしたポケモンで、イボのついた、大きくて明るい色のポケモンボールのような帽子をかぶっています。また、灰色の巨大な茎のような体、獰猛そうな目、そして大きなピンクの口を持っています。 モロバレルは、2つのポケモンボールのような盾を手にしています。腕にあるポケモンボールのような模様を使って獲物を誘い込もうとしますが、たいていの場合、あまりうまくいきません。また、相手に有毒な胞子を吹きかけます。これらの胞子は、すぐに洗い流さないと、着地した場所でキノコに成長してしまいます。モロバレル' WHERE character_id = 'CH014877';
UPDATE characters SET description = 'コジロウはロケット団の一員であり、具体的にはムサシやニャースと3人組を組んで、『ポケットモンスター』のアニメでサトシとその仲間たちを追いかけ回しており、たいていはサトシのピカチュウを盗もうとしている。' WHERE character_id = 'CH014879';
UPDATE characters SET description = '大木戸ユキナリは、『ポケットモンスター』アニメに登場するポケモン教授であり、主要な脇役の一人。マサラ町の研究所で生活し、研究活動を行っている。サトシが「最強のポケモンマスター」になるという目標を達成できるよう、時折アドバイスを与えるために登場する。   (出典：Bulbapedia)' WHERE character_id = 'CH014880';
UPDATE characters SET description = 'ミジュマルは、ラッコに似た二足歩行のポケモンです。頭は球形で白く、両脇には小さな三角形の紺色の耳があります。ミジュマルの目は黒く、濃いオレンジ色の鼻は横長の楕円形をしています。 頬にはそばかすのようなものがいくつかあり、これは未発達のひげかもしれない。口を開けると、2本の尖った歯が見える。体の水色の毛は、首の周りに泡のような形を作っている。腕は白く丸みを帯びており、足は濃い青色で、それぞれ3本の指がある。また、ポ' WHERE character_id = 'CH014881';
UPDATE characters SET description = 'ラプラスは、プレシオサウルスに似た大きな海のポケモンです。青い体には濃い青の斑点があり、腹側はクリーム色をしています。大きな茶色の目、額には短い角、そしてきつくカールした耳を持っています。首は長く、4つのひれがあります。 前方のひれは後方のひれよりも大きい。背中には、鈍い突起で覆われた重厚な灰色の甲羅がある。ラプラスは穏やかで親切なポケモンで、人々を水域の向こう岸へ運ぶことを楽しんでいる。かつては、そのおとなしい性格ゆえに、' WHERE character_id = 'CH014882';
UPDATE characters SET description = 'デスマスは、かつて人間だった頃の顔が刻まれた金色の仮面を手にした、影のようなポケモンです。影のようなつる状の腕を2本持ち、大きな赤い目を持っています。また、仮面を支える小さな尾のような突起もあります。 デスマスは人間に取り憑いた時には話すことができますが、通常の姿では話すことができません。はるか昔に人間だったため、人間だった頃の記憶を持っています。仮面を失ったり、奪われたりすると激怒します。デスマスが持っている仮面を誰かが被ると、その人はデスマスに取り憑かれてしまいます。' WHERE character_id = 'CH014883';
UPDATE characters SET description = 'ムサシはロケット団の一員であり、具体的にはコジロウやニャースと3人組を組んで、『ポケットモンスター』のアニメでサトシとその仲間たちを追いかけ回しており、たいていはサトシのピカチュウを盗もうとしている。' WHERE character_id = 'CH014884';
UPDATE characters SET description = 'ジェニー警官は単一の存在ではありません。むしろ、ポケモン世界のさまざまな地域で、多くのジェニーが警察官として働いています。  一般的に、ジェニー巡査たちは勇敢で意志が強いですが、警察としての職務においてはほとんど成果を上げていません。彼女たちは、ロケット団、マグマ団、アクア団、ギャラクティック団といった組織や、その他さまざまな犯罪者たちと戦っています。特定のジェニーがどこの町や地域出身かは、帽子についたシンボルで見分けることができます。このシンボルは場所によって常に異なります。' WHERE character_id = 'CH014885';
UPDATE characters SET description = 'カイリュウは、薄オレンジ色の肌を持つ、竜のような二足歩行のポケモンです。灰緑色の大きな目と、小さな鼻孔のある丸い鼻を持っています。頭頂部からは一対の細長い触角が生えており、その間に小さな角があります。 腹部はクリーム色の縞模様で、首から長く先細りの尾の先端まで続いている。太い腕と脚を持ち、それぞれ先端には3本の爪がある。脚の関節はくっきりと際立っている一方、腕は滑らかで丸みを帯びた外観をしている。カイリュウの翼は小さい。' WHERE character_id = 'CH014886';
UPDATE characters SET description = 'ヒコザルは、チンパンジーに似た二足歩行のポケモンです。毛並みは主にオレンジ色ですが、顔、耳の外側、腹、手、足は淡い黄色をしています。お尻には小さくて丸い赤い斑点がありますが、通常は胃の中でガスが燃えて生じる炎に隠れています。 この炎は眠ると消え、体調が悪いときは弱く燃え続けます。耳は頭の大きさに比べて大きく、内側は赤いです。上顎には2本の尖った歯があります。ヒコザルの体には赤い模様が…' WHERE character_id = 'CH014887';
UPDATE characters SET description = 'ヘラクロスは、青い外骨格に覆われた、カブトムシのような二足歩行のポケモンです。額には、先端が分かれた長い角が生えています。この角の先端は、オスでは十字形、メスではハート形になっています。角の両側には、先端が球形の短い触角があります。 ヘラクロスの目は楕円形で黄色い。前腕の手首付近には2本のトゲがあり、太ももにはそれぞれ1本ずつトゲがある。手には2本の爪があり、足にはそれぞれ1本ずつ長い爪がある。翼は1対あり、その翼は' WHERE character_id = 'CH014888';
UPDATE characters SET description = 'ガンガーは、丸みを帯びた体を持つ、濃い紫色の二足歩行のポケモンです。赤い目と、普段は不気味な笑みを浮かべているような大きく開いた口、そして尖った耳が特徴です。背中には無数のトゲがあり、頭頂部にはふさふさした毛のような小さなトゲが生えています。 手足は短く、手足にはそれぞれ3本の指がある。また、太く短い尾も持っている。ガンガーはあらゆる物体の影に完璧に身を隠す能力を持ち、並外れたステルス性を発揮する。しかし、ガンガーの体は熱源として機能し、' WHERE character_id = 'CH014889';
UPDATE characters SET description = 'イワークは、尾の方に向かって次第に小さくなる巨大な灰色の岩の連なりで構成されたポケモンです。その長さから、岩タイプのポケモンの中で最も背が高い存在となっています。黒い目と丸みを帯びた鼻を持ち、頭頂部には岩のような棘があります。年を重ねるにつれて、その体はより丸みを帯び、滑らかになり、最終的には黒いダイヤモンドのような姿になります。 脳の中には磁石があり、これが体内コンパスとして機能し、イワークが行くべき場所へと導き、穴を掘っている最中に道に迷うのを防いでいます。イワークはトンネルを掘ります' WHERE character_id = 'CH014890';
UPDATE characters SET description = 'ツタルジャは、ほっそりとした体型の二足歩行の爬虫類型のポケモンです。体の大部分は緑色で、腹側はクリーム色をしています。背中と尻尾には黄色い縞模様が縦に走り、大きな目の周りには黄色い模様があります。 肩からは、葉や小さな翼のような2つの湾曲した黄色い構造物が突き出ており、後ろ向きに反り返っている。ほっそりとした腕には3本の指があるが、小さな足には指が全くない。尾の先端には、先端が3つに分かれた大きな掌状の葉がある。この尾は' WHERE character_id = 'CH014891';
UPDATE characters SET description = 'ネートルは、カメやリクガメに似た、小さくて薄緑色の四足歩行のポケモンです。目、足、下顎は黄色です。体は土でできた茶色の甲羅で覆われています。甲羅には太い黒い縞模様と黒い縁取りがあります。 とても健康なネートルの甲羅は、触るとしっとりしているはずです。頭にある茶色の部分に小さな苗が生えています。この苗は、ポケモンが喉が渇くとしおれてしまいます。植物系のポケモンであるネートルは、通常、光合成によって栄養を補給しています。また、水を飲むことも' WHERE character_id = 'CH014892';
UPDATE characters SET description = 'ゴマゾウは、小さな青い象のようなポケモンです。大きくて垂れ下がった耳を持っており、それを扇子のように使って体を冷やしています。それぞれの耳には2つの赤いパッドがあり、短い鼻の付け根にももう1つあります。 この小さな鼻は敏感でありながら、とても力強い。愛情を込めてふざけて鼻先で軽くぶつけるだけで、人を吹き飛ばすことさえできる。さらに、この小さなポケモンは、大人の人間を背中に乗せることも難なくこなす。ゴマゾウは4本の足にそれぞれ1本ずつ爪があり、尾は短い。ゴマゾウはロック' WHERE character_id = 'CH014893';
UPDATE characters SET description = 'チコリータは、首の周りに濃い緑色のつぼみがついた、淡い緑色の小さなポケモンです。頭は体に対して大きく、大きな赤い目を持っています。4本の短い足にはそれぞれ爪のある指が1本ずつあり、しっぽは短く太いです。 頭の上には、たいてい体長よりも長い大きな緑の葉が生えています。その葉からは心地よい香りが漂い、戦っているポケモンを落ち着かせることができます。また、この葉は温度や湿度を感知するためにも使われています。チコリータは積極的に太陽の暖かさを求め、それを楽しんでいます。' WHERE character_id = 'CH014894';
UPDATE characters SET description = 'ゼニガメは、水色のカメに似た小さなポケモンです。紫がかった、あるいは赤みがかった大きな目と、わずかに上向きに曲がった上唇が特徴です。手足にはそれぞれ3本の尖った指があります。長い尾の先端は内側にカールしています。 その体は、生まれてから形成・硬化していく頑丈な甲羅に覆われている。この甲羅は上面が茶色、下面が淡黄色で、甲羅の左右の半分の間には分厚い白い隆起がある。ゼニガメの甲羅は便利な道具だ。身を守るためや、' WHERE character_id = 'CH014895';
UPDATE characters SET description = 'ジュプタイルは、獣脚類の恐竜に似た外見を持つ二足歩行のポケモンです。体は主に緑色で、腹側は赤色をしています。腹にはベルトのような緑色の縞模様が横切っています。ジュプタイルの手には2本の爪のある指があり、鳥のような足を持つ力強い脚を持っています。 発達した筋肉のおかげで、登り上手であり、枝から枝へと素早く飛び移ることができます。ジュプタイルの手首には3枚の長い葉があり、頭頂部には大きな葉、そして葉のような見た目の尾が2本あります。この葉のような見た目は、' WHERE character_id = 'CH014896';
UPDATE characters SET description = 'ラティアスは、飛行機をモチーフにした鳥のような姿をしたポケモンです。ずんぐりした体から長い首が前方に伸びています。足はなく、普段は空中に浮かんでいます。体の後半部分は主に赤く、上半身は白く、背中の高い位置にはジェット機の翼があり、尾の近くの下部にはひれがあります。 胸の中央には青い三角形があり、顔の一部は赤いマスクで覆われています。頭の上には耳のようなひれがあり、目は黄色です。短く、3本の指を持つ腕があり、その先には……' WHERE character_id = 'CH014897';
UPDATE characters SET description = 'ラティオスは、第3世代で登場した「ドラゴン・エスパー」の2つのタイプを持つ伝説のポケモンです。' WHERE character_id = 'CH014898';
UPDATE characters SET description = 'プルリルは、若き王族を思わせるクラゲのようなポケモンです。性別に関わらず、王冠のような房のある丸い頭と、5本の触手のような付属肢を持っています。そのうち2本は腕として、3本は下半身として機能しています。 目は楕円形で瞳孔は白く、首の周りには襟のような模様がある。付属肢には目に見えない毒の棘がある。オスのプルリルは青色で、付属肢は滑らか、王冠は三角形をしている。目は赤く、白目は青く、両目に1本ずつまっすぐなまつげがあり、その襟は' WHERE character_id = 'CH014899';
UPDATE characters SET description = 'デリバードは、赤いペンギンのようなポケモンで、白く中空の尾を持っています。顔と胸は白い羽で覆われており、目の上には2つの三叉のトサカがあります。丸い目の周囲には黒い模様があり、くちばしと足は淡い黄色をしています。 お腹には白い斑点が一つある。足にはそれぞれ2本の指がある。デリバードは雑食性で、尾に食べ物を束ねて運ぶ。普段は蓄えた食べ物を雛に与えるが、氷の海で立ち往生した人間と食べ物を分け合うこともある。' WHERE character_id = 'CH014900';
UPDATE characters SET description = 'アニメ：サカキはロケット団のボスであり、かつてはトキワシティのジムリーダーを務めていた。彼は非常に野心家であり、失敗を一切許さない。サカキは莫大な富と資源を手にしていることが示されている。 その資金は、おそらくロケット団の主な収入源である、盗んだポケモンの売却益に由来している。また、サカキはポケモンの密輸やポケモンボールの密売、その他の犯罪活動からも多額の資金を得ている。彼は関東とジョウトの両方でロケット団の活動を展開している。彼はめったに人々と直接会うことはなく、その理由は……' WHERE character_id = 'CH014901';
UPDATE characters SET description = 'コロモリは、ホンジュラスシロコウモリに似た、青い球形のポケモンです。体中はふさふさした毛で覆われており、豚のような大きな鼻にはハート型の鼻孔があります。2つのふさふさした毛の房が目を隠しており、口の上顎の中央には1本の牙があります。 体の両側には、比較的小さな黒い翼が2枚あります。コロモリの鼻にはさまざまな役割があります。鼻孔から超音波を発してエコーロケーションを行うほか、眠っているときに壁にしがみつくのにも使われます。' WHERE character_id = 'CH014902';
UPDATE characters SET description = 'ドラルクは、名門ドラゴン一族に属する不死の高等吸血鬼だが、些細なことで何度も死んでしまい、塵と化してしまう。城が破壊されたため、彼はロナウドの家に居候することになったが、ロナウドはそれを大いに快く思っていなかった。 ドラルクは、青白く骨ばった顔立ちに、尖った耳と鼻を持つ、典型的な大人の吸血鬼の外見をしている。丸く、少し垂れ下がった目をしていて、短い黒髪を後ろに撫でつけている。' WHERE character_id = 'CH014903';
UPDATE characters SET description = 'ジョンはオスのアルマジロで、ドラルクの使い魔である。人間の言葉は理解できるが、話すことはできない。彼の言葉を理解できるのはドラルクだけであるため、ジョンは身振りや手話を使って他者と意思疎通を図っている。ドラルクの使い魔として正式に認められた後、彼は不老不死の力を得た。' WHERE character_id = 'CH014904';
UPDATE characters SET description = '新横浜を拠点とする20代の吸血鬼ハンター。 当初はドラルクをルームメイトに迎えることに乗り気ではなかったが、小説シリーズ『ロナウド・クロニクルズ』でのパートナーシップが成功したため、しぶしぶその吸血鬼を受け入れるようになった。イライラすると頻繁にドラルクを殺してしまう。また、セロリに対して極度の恐怖症を抱いている。' WHERE character_id = 'CH014905';
UPDATE characters SET description = 'ロナウドのギルドに所属する吸血鬼ハンターで、左腕に金属製の鎧をまとっている。更生した元不良であり、たいていの状況では冷静さを保っているが、怒らせると過去の面影が表れてしまう。' WHERE character_id = 'CH014906';
UPDATE characters SET description = 'オータム・ブックスのロナウド担当編集者。オータム・ブックスの社員全員と同様に、戦斧を振るう、恐ろしいほど冷静な男だ。締め切りを守るよりも猫を愛している。' WHERE character_id = 'CH014907';
UPDATE characters SET description = '弓を使って戦う吸血鬼ハンター。' WHERE character_id = 'CH014909';
UPDATE characters SET description = '近所に住んでいる普通の猫' WHERE character_id = 'CH014911';
UPDATE characters SET description = 'ロナウドのギルドに所属するもう一人のハンター。体毛のある女の子にフェチがある。どこかアメリカ南西部風の服装をしている。' WHERE character_id = 'CH014914';
UPDATE characters SET description = 'ドラウスはドラルクの父である。彼は不死の高等吸血鬼であり、おそらくドラゴン一族の次期当主となるだろう。' WHERE character_id = 'CH014915';
UPDATE characters SET description = 'かつては吸血鬼ハンターだったが、現在はギルドのバーテンダーを務めている。ギルドに寄せられる依頼を受け付け、割り当てを行っている。' WHERE character_id = 'CH014916';
UPDATE characters SET description = '廃病院に住む幽霊。カハンシン・トウメイとは仲が良い。' WHERE character_id = 'CH014917';
UPDATE characters SET description = 'ボンデージを用いて、自分より劣る吸血鬼を訓練し、支配する吸血鬼トレーナー。' WHERE character_id = 'CH014918';
UPDATE characters SET description = '性的なことばかり考えてしまうため、変身能力をほとんど制御できない吸血鬼。彼の真の姿はハンサムな金髪の吸血鬼だが、その姿になれるのは、欲求が満たされたときか、あるいは完全に興ざめしたときだけである。' WHERE character_id = 'CH014920';
UPDATE characters SET description = '彼女は、アダムが自分の友人に対して見せた軽薄な態度を、自分に向けられたものと勘違いし、彼をストーカーし始め、彼に噛まれることさえ喜んで受け入れた。' WHERE character_id = 'CH014923';
UPDATE characters SET description = 'ロナウドのギルドに所属するハンターで、チャイナドレス風の衣装を身にまとった小柄な少女。率直で物言いがきつい性格で、的を射た個人攻撃的な侮辱で知られている。' WHERE character_id = 'CH014924';
UPDATE characters SET description = 'ヤキュケンが大好きな吸血鬼で、対戦相手を突破不可能なバリアの中に閉じ込めてプレイする。負けた方は服を脱がされる。' WHERE character_id = 'CH014925';
UPDATE characters SET description = '吸血鬼研究センターの、著名で才気あふれる所長。' WHERE character_id = 'CH014926';
UPDATE characters SET description = 'ヴァミマ店の店長のご子息。' WHERE character_id = 'CH014928';
UPDATE characters SET description = 'コンビニ「ヴァミマ」の店長であり、タケオの父親。' WHERE character_id = 'CH014929';
UPDATE characters SET description = '「オータム・ブックストア」の編集者。' WHERE character_id = 'CH014933';
UPDATE characters SET description = 'ロナウドのギルドに所属する、修道女の格好をした巨乳のハンター。主な仕事はマタギとして熊を狩ることだ。' WHERE character_id = 'CH014934';
UPDATE characters SET description = '3組の唇を持つ奇妙な姿の吸血鬼で、若くてハンサムな男性を標的にし、キスを通じて血を吸う。' WHERE character_id = 'CH014935';
UPDATE characters SET description = 'ゴウセツの娘。「新横浜ハイボール」でバーテンダーとして働いている。' WHERE character_id = 'CH014936';
UPDATE characters SET description = 'かつては連続殺人鬼だった吸血鬼だが、新横浜に入ってからというもの、かつての面影は影も形もなく、みすぼらしい姿と化している。彼は自分の血を刃に変え、たいていは手のひらからそれを生み出す。' WHERE character_id = 'CH014937';
UPDATE characters SET description = 'マレミの妹。' WHERE character_id = 'CH014938';
UPDATE characters SET description = '下半身が透明な、高位の吸血鬼。' WHERE character_id = 'CH014941';
UPDATE characters SET description = '吸血鬼ハンター。' WHERE character_id = 'CH014942';
UPDATE characters SET description = '身につけているマイクロビキニから力を引き出す吸血鬼。彼が噛んだ相手は誰でもマイクロビキニを身にまとい、彼の支配下に入る。彼は『ヤクユケン・ラバー』の弟である。' WHERE character_id = 'CH014943';
UPDATE characters SET description = '自称「新横浜・ボーイハンターズ」のメンバー。吸血鬼狩りをする小学生の男の子3人組。' WHERE character_id = 'CH014944';
UPDATE characters SET description = '催眠術を使って、人々に秘めたフェチを口に出させる、中年の風貌をした吸血鬼。ドラウスの旧知の仲である。' WHERE character_id = 'CH014945';
UPDATE characters SET description = '吸血鬼を殲滅するために新横浜にやってきたダンピール。' WHERE character_id = 'CH014946';
UPDATE characters SET description = '吸血鬼ハンター。' WHERE character_id = 'CH014947';
UPDATE characters SET description = '股間がゼラニウムの群れで隠された、ほぼ全裸の吸血鬼。彼は植物や、種を与えた相手を意のままに操ることができる。' WHERE character_id = 'CH014948';
UPDATE characters SET description = '自称「新横浜・ボーイハンターズ」のメンバー。吸血鬼狩りをする小学生の男の子3人組。' WHERE character_id = 'CH014949';
UPDATE characters SET description = '半田トウの吸血鬼の母親。彼女はロナウドの大ファンだ。' WHERE character_id = 'CH014950';
UPDATE characters SET description = 'ドラルクの祖父。一族の長であり、一族の中で最も強い。' WHERE character_id = 'CH014951';
UPDATE characters SET description = '吸血鬼対策課の警官。同課史上最年少の副課長である。勤務中は二刀流を駆使する。一見、堅くて厳しい印象を与えるが、実はすぐに動揺してしまう。ドラルクの料理、特にクッキーが大好きだ。' WHERE character_id = 'CH014953';
UPDATE characters SET description = 'ヴァンパイア対策課の課長であり、ロナウドの兄。かつてはハンターだった。' WHERE character_id = 'CH014954';
UPDATE characters SET description = 'グールを操る吸血鬼。ゴミをポイ捨てするなど、マナー違反を犯す。' WHERE character_id = 'CH014955';
UPDATE characters SET description = '自称「新横浜・ボーイハンターズ」のリーダー。吸血鬼狩りをする小学生の男の子3人組。' WHERE character_id = 'CH014956';
UPDATE characters SET description = 'ヴァンパイア対策課の隊員。' WHERE character_id = 'CH014957';
UPDATE characters SET description = 'ドラルクの母親。' WHERE character_id = 'CH014958';
UPDATE characters SET description = 'アヒルをモチーフにした吸血鬼ハンター。彼はとても人気がある。' WHERE character_id = 'CH014962';
UPDATE characters SET description = 'ヒナイチの部下。ダンピールであり、ロナウドの高校時代の同級生。マザコン気質の彼は、吸血鬼である母親がロナウドの著作のファンであることを嫌っており、ハンターであるロナウドのあまり見栄えのしない一面を母親に見せつけようとしている。その憎しみは執着に近いほどで、彼の部屋はロナウドのポスターやグッズで埋め尽くされている。' WHERE character_id = 'CH014963';
UPDATE characters SET description = '吸血鬼対策課の比較的新しいメンバーの一人。彼は自分の仕事をかなり真剣に受け止めている。' WHERE character_id = 'CH014964';
UPDATE characters SET description = 'バットとボールを使って戦う吸血鬼ハンター。' WHERE character_id = 'CH014965';
UPDATE characters SET description = '青西高校柔道部の部員。アンナとミチは小学校からの同級生で、最も長く付き合いのある仲だ。高校では剣道部に入部し、すぐにレギュラーの座を勝ち取り、剣道部を全国大会へと導いた。 しかし、ミチと同じ部活に入りたいという思いが拭えず、柔道部へ転部した。彼女は機会があるたびに自分を「天才」と称するが、日々の努力を怠ることは決してなく、学業でも' WHERE character_id = 'CH014970';
UPDATE characters SET description = '青西高校柔道部の部員で、ミチの親友。体重階級は57kg。成績優秀で才能あふれる少女であり、中学時代にはクラスで2位の成績を収めていた。 また、勉強が苦手なミチには家庭教師役も務めており、彼女に的確なアドバイスを与えられる数少ない人物の一人でもある。サナエの柔道の実力は、体力・技術ともに平凡だが、粘り強く、相手を抑え込みの技に持ち込むのが得意だ。' WHERE character_id = 'CH014971';
UPDATE characters SET description = '『もう一本』の主人公。無邪気な性格で、誰とでも気兼ねなく話しかけ、人付き合いも上手だ。 ミチは場の空気を読めないため、騒がしい人が苦手な人からは時々「少し厄介」だと思われることもあるが、他人の長所や努力を率直かつ誠実に認め、称賛することができるため、周囲からは好かれている。   小柄ではあるが、体がしなやかで胴回りがしっかりしており、その体格は……' WHERE character_id = 'CH014972';
UPDATE characters SET description = '青西高校柔道部のエース。体重階級は52kg級。中学時代に道と対戦したことをきっかけに、私立高校への推薦入学を辞退し、道と同じ青西高校に入学した。 ヒウラは、部員たちやナツメからも認められている青西の主力選手であり、体は細身だが、体力には優れている。普段は控えめで口数の少ない彼女だが、柔道着を着ると、ヒウラの表情はまるで別の人のように引き締まる。' WHERE character_id = 'CH014973';
UPDATE characters SET description = '背の高い女性体育教師で、青西高校柔道部の顧問を務めている。篠は顧問に就任してから本格的に柔道を始めたが、初段という段位にもかかわらず、乱取りでは常に勝利を収めるほどの強さを見せている。 彼女は力強い柔道だけでなく、知的な柔道も習得しており、そのことは指導ぶりからも明らかだ。シノは、部員の個性や能力、そして舞台裏での努力を見逃さない鋭い観察眼を持っている。' WHERE character_id = 'CH014979';
UPDATE characters SET description = '霞ヶ丘高校柔道部のエースで、川北中学校出身。ミチより1歳年上だ。エリカは52kg級に所属している。北川中学校ではヒウラの後輩であり、体格は彼女とほぼ同じだ。' WHERE character_id = 'CH014980';
